### ISSUE TITLE
Compilation of NWChem 7.0.0

### ISSUE THREAD

**Issue by zyzhang1992** [nwchemgit/nwchem#249] opened 2020-09-14 18:56 UTC
Hi there, 

I am compiling NWChem 7.0.0 on AMD architectures and got the following error: 

make[1]: Entering directory `/home/groups/ruthm/zyzhang/sw/sherlock3/nwchem/nwchem-7.0.0.rme.openmpi.4.0.5/src/basis'
Compiling basis.F...
gfortran: error: unrecognized command-line option '-i8'; did you mean '-k8'?

Here is the compilation configurations: 

gcc/10.1.0 openmpi/4.0.5

export NWCHEM_TOP=/home/groups/ruthm/zyzhang/sw/sherlock3/nwchem/nwchem-7.0.0.rme.openmpi.4.0.5
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI_PR
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y

export LARGE_FILES=TRUE
export USE_NOFSCHECK=TRUE
export LIB_DEFINES=-DDFLT_TOT_MEM=16777216
export MRCC_THEORY=TRUE
export NWCHEM_KEEPF=TRUE

export MRCC_METHODS=TRUE
export CCSDTQ=TRUE

export BLASOPT="-lblis"
export LAPACK_LIB=-lblis

export USE_SCALAPACK=y
export SCALAPACK=/share/software/user/open/scalapack/2.1

export PYTHONHOME=/share/software/user/open/python/2.7.13
export PYTHONVERSION=2.7
export USE_PYTHONCONFIG=Y

cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES="all python"
make clean

export USE_64TO32=y  
export BLAS_SIZE=4

make 64_to_32
export CC=mpicc FC=mpif90

make >& make.log 

Thanks!

Zhiyong

**Comment by hjjvandam** [comment] 2020-09-14 19:06
Hi Zhiyong,

I think you have got most things right. The problem is in the line:


                export CC=mpicc FC=mpif90

make >& make.log
NWChem uses the compiler names to work out what compiler flags to use for some features. The MPI compiler wrapper scripts hide the name of the actual compiler and as a result it picked the flags for a compiler other than the GCC compilers you are actually using. Hence, if you replace the above two lines with


                export CC=gcc FC=gfortran

make >& make.log
then the Makefile will choose the correct compiler flags and with that the compilation should succeed.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by edoapra** [comment] 2020-09-14 19:07
Please do not use neither mpicc nor mpif90 as compiler names.
If you want to use gfortran and gcc and they are in your input, just typing
```
 make
```
is going to work

**Comment by zyzhang1992** [comment] 2020-10-01 18:39
Thanks Huub and Edo! I was able to compile following your advises. I was trying to link against libflame but seems like NWChem uses some subroutines that is not implemented in libflame when running the tests in the installation. 

libflame: src/lapack/red/tridiagut/front/flamec/FLA_Tridiag_UT_internal.c (line 26):
libflame: Function or conditional branch/case not yet implemented.
libflame: Aborting.

Program received signal SIGABRT: Process abort signal.

Has anybody ever tried to link against libflame? 

For taking advantage of the locally optimized libraries, what do you recommend for the AMD architectures?  

Thanks!

Zhiyong

**Comment by jeffhammond** [comment] 2020-10-01 18:54
NWChem includes LAPACK.  Build that and link it to the right of libflame and it will get used for the missing symbols.  Please also report this issue to libflame GitHub.

**Comment by hjjvandam** [comment] 2020-10-01 18:57
Hi Zhiyong,
From what I remember the critical component for which you need good performance is BLAS. For a while OpenBLAS was popular (https://github.com/xianyi/OpenBLAS), but these days it seems that BLIS (https://github.com/flame/blis) is used more. You can build the usual Netlib reference version of LAPACK as long as you use the optimized BLAS underneath it (don’t use the Netlib BLAS!).

An interesting observation is that the error you got is that in the function FLA_Tridiag_UT_internal only the lower triangle diagonalization is implemented. The upper triangle diagonalization isn’t. This is interesting because in most cases NWChem will compute the whole matrix, and so you can equally pick either the upper or lower triangle. So you might want to check if you can find which diagonalization call is going wrong, and if you can just change UPLO to fix this problem.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by zyzhang1992** [comment] 2020-10-01 19:37
Thanks Jeff and Huub. I did raise the issues with the libflame developers. They believed that it is straightforward to implement the uplo. As typically the case they just do not have the support and bandwidth to work that that now. There may be other inconsistencies when calling libflame from NWChem. Here is the link to that discussion: 

https://groups.google.com/g/libflame-discuss/c/tQXNQYd-EVE/m/gf0kdBgYDgAJ?pli=1

Jeff, thanks for the suggestion of nwchem lapack. I'll give that a try when I have a chance. 

Best, 

Zhiyong

**Comment by edoapra** [comment] 2020-10-01 19:51
@zyzhang1992 it seems that your stumbling block is installing ScaLapack isn't it?
If this is the case, my recommendation is to use the hotfix/release-7-0-0 branch (a.k.a upcoming 7.0.1)
and defined the following env. variables
```
BUILD_SCALAPACK=1
BUILD_OPENBLAS=1
BLAS_SIZE=8
SCALAPACK_SIZE=8
```
These settings will trigger the build of ScaLapack and OpenBLAS (that includes Lapack) with 64-bit integers, therefore not requiring the `make 64_to_32 USE_64TO32=1` step

**Comment by zyzhang1992** [comment] 2020-10-02 21:08
Thanks Edo. That worked perfectly. I see the gcc is all -g only. Do you have a version of the makefile that compile an optimized version?

**Comment by edoapra** [comment] 2020-10-03 01:38
Zhiyong, what part of the compilation are you referring to?

**Comment by zyzhang1992** [comment] 2020-10-03 06:52
Looks like it is the openblas, make[4]: 

Entering directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/openblas/OpenBLAS-0.3.10/interface'
gcc -g -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT  -fPIC -DNO_LAPACKE -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.10\" -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o

grep of make log  show ca. 1900 gcc's and out of those ca. 1300 is -g -o and the others looks like just gcc -g

**Comment by edoapra** [comment] 2020-10-03 17:47
Zhiyong thanks for spotting this. I have just committed a change that should disable debugging while build OpenBLAS. I am currently testing in the master branch. If testing proves to be successful, I will commit the same change to hotfix/release-7-0-0

**Comment by edoapra** [comment] 2020-10-05 17:24
Zhiyong, if you perform a `git update` and recompile, after a `make clean`, the directory `$NWCHEM_TOP/src/libext`, you should get a compilation with `-O`

**Comment by zyzhang1992** [comment] 2020-10-05 21:52
Thanks Edo. I am on the master branch and then git pull to update the branch and did make clean in src/libext When I make, 

for dir in libext libext tools include basis geom inp input pstat rtdb task symmetry util peigs perfm bq cons  NWints atomscf ddscf gradients moints nwdft rimp2 stepper driver optim cphf ccsd vib mcscf prepar esp hessian selci dplot mp2_grad qhop property solvation nwpw fft python analyz nwmd cafe space drdy vscf qmmm qmd etrans tce bq mm cons perfm dntmc dangchang ccca dimqm; do \
        echo Making include_stamp in /home/groups/ruthm/zyzhang/sw/nwchem/src/$dir ; \
        (cd /home/groups/ruthm/zyzhang/sw/nwchem/src/$dir; make include_stamp) ; \
done
Making include_stamp in /home/groups/ruthm/zyzhang/sw/nwchem/src/libext
make[2]: Entering directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/libext'
make[2]: `include_stamp' is up to date.
make[2]: Leaving directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/libext'
Making include_stamp in /home/groups/ruthm/zyzhang/sw/nwchem/src/libext
make[2]: Entering directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/libext'
make[2]: `include_stamp' is up to date.
make[2]: Leaving directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/libext'
Making include_stamp in /home/groups/ruthm/zyzhang/sw/nwchem/src/tools
make[2]: Entering directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/tools'
make[2]: *** No rule to make target `include_stamp'.  Stop.

So doesn't look that it is recompiling the libraries?

**Comment by edoapra** [comment] 2020-10-05 22:42
Can you try the following steps, verbatim
```
cd $NWCHEM_TOP/src/libext
make clean
make
cd ..
make link
```

**Comment by zyzhang1992** [comment] 2020-10-06 00:56
That seems to have worked for the compilation but there is a problem with linking, missing fcidump_

gfortran   -L/home/groups/ruthm/zyzhang/sw/nwchem/lib/LINUX64 -L/home/groups/ruthm/zyzhang/sw/nwchem/src/tools/install/lib   -o /home/groups/ruthm/zyzhang/sw/nwchem/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil  -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_scalapack  -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_openblas       -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_openblas  -L/home/groups/ruthm/zyzhang/sw/sherlock2/openmpi/4.0.5-gcc-10.1.0/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi    -lcomex -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lnwc_openblas -lrt -lpthread -lm -lpthread  -lnwcutil -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic  
/home/groups/ruthm/zyzhang/sw/nwchem/lib/LINUX64/libnwctask.a(input_parse.o): In function `input_parse_':
/home/groups/ruthm/zyzhang/sw/nwchem/src/input/input_parse.F:213: undefined reference to `fcidump_input_'
/home/groups/ruthm/zyzhang/sw/nwchem/lib/LINUX64/libnwctask.a(task.o): In function `task_':
/home/groups/ruthm/zyzhang/sw/nwchem/src/task/task.F:406: undefined reference to `task_fcidump_'
/home/groups/ruthm/zyzhang/sw/nwchem/lib/LINUX64/libmoints.a(moints_full.o): In function `moints_full_':
/home/groups/ruthm/zyzhang/sw/nwchem/src/moints/moints_full.F:350: undefined reference to `fcidump_symm_'
/home/groups/ruthm/zyzhang/sw/nwchem/src/moints/moints_full.F:360: undefined reference to `fcidump_symm_'

**Comment by edoapra** [comment] 2020-10-06 00:59
Please send the output of this sequence of commands
```
cd $NWCHEM_TOP/src
make nwchem_config
make link
```

**Comment by zyzhang1992** [comment] 2020-10-06 01:15
Here is the make link output, probably I need to make first before make link?

gfortran   -L/home/groups/ruthm/zyzhang/sw/nwchem/lib/LINUX64 -L/home/groups/ruthm/zyzhang/sw/nwchem/src/tools/install/lib   -o /home/groups/ruthm/zyzhang/sw/nwchem/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lfcidump -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil  -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_scalapack  -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_openblas       -L/home/groups/ruthm/zyzhang/sw/nwchem/src/libext/lib -lnwc_openblas  -L/home/groups/ruthm/zyzhang/sw/sherlock2/openmpi/4.0.5-gcc-10.1.0/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi    -lcomex -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lnwc_openblas -lrt -lpthread -lm -lpthread  -lnwcutil -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
/usr/bin/ld: cannot find -lfcidump
collect2: error: ld returned 1 exit status
make: *** [link] Error 1

below is the make config output

make nwchem_config NWCHEM_MODULES="all python"
make -C config -f make_nwchem_config NWCHEM_MODULES="all python"
make[1]: Entering directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/config'
echo \# This configuration generated automatically on \
      `hostname` at `date` > nwchem_config.h
echo "# Request modules from user: all python" >> nwchem_config.h
echo "NW_MODULE_SUBDIRS = NWints atomscf ddscf gradients moints nwdft rimp2 stepper driver optim cphf ccsd vib mcscf prepar esp hessian selci dplot mp2_grad qhop property solvation nwpw fft python analyz nwmd cafe space drdy vscf qmmm qmd etrans tce bq mm cons perfm dntmc dangchang ccca dimqm fcidump" >> nwchem_config.h
echo "NW_MODULE_LIBS = -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lfcidump" >> nwchem_config.h
echo "EXCLUDED_SUBDIRS = develop nwxc scfaux rimp2_grad argos diana uccsdt rism geninterface smd nbo leps lucia rdmft" >> nwchem_config.h
echo "CONFIG_LIBS = " >> nwchem_config.h
echo \# This configuration generated automatically on \
     `hostname` at `date` > NWCHEM_CONFIG
echo "# Request modules from user: all python" >> NWCHEM_CONFIG
echo The following subdirectories are built: >> NWCHEM_CONFIG
echo NWints analyz atomscf bq cafe ccca ccsd cons cphf dangchang ddscf dimqm dntmc dplot drdy driver esp etrans fcidump fft gradients hessian mcscf mm moints mp2_grad nwdft nwmd nwpw optim perfm prepar property python qhop qmd qmmm rimp2 selci solvation space stepper symmetry tce vib vscf >> NWCHEM_CONFIG
echo corresponding to these libraries: >> NWCHEM_CONFIG
echo -lnwints -lanalyze -lguess -lbq -lcafe -lccca -lccsd -lcons -lcphf -ldangchang -lddscf -ldimqm -ldntmc -ldplot -ldrdy -ldriver -lesp -letrans -lfcidump -lpfft -lgradients -lhessian -lmcscf -lmm -lmoints -lmp2 -lnwdft -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -loptim -lperfm -lprepar -lproperty -lnwpython -lqhop -lqmd -lqmmm -lrimp2 -lselci -lsolvation -lspace -lstepper -lnwcutil -ltce -lvib -lvscf >> NWCHEM_CONFIG
echo >> NWCHEM_CONFIG
echo The following directories are excluded from the build: >> NWCHEM_CONFIG
echo develop nwxc scfaux rimp2_grad argos diana uccsdt rism geninterface smd nbo leps lucia rdmft >> NWCHEM_CONFIG
echo and these routines will be replaced by stubs: >> NWCHEM_CONFIG
echo argos argos_input crossing debtest dia_input diana gasdev geninterface jantest jvltest jvltest2 kgdtest leps_energy leps_gradient lucia mc_data mc_driver mc_init mc_main md_data md_driver md_set moints_screen mymc_input mymd_input nbo_input nwxc_eval_df nwxc_eval_df2 nwxc_eval_df3 nwxc_get_cam nwxc_get_disp nwxc_getvals nwxc_getwght nwxc_has_2nd nwxc_has_cam nwxc_has_disp nwxc_has_hfx nwxc_has_mp2c nwxc_has_xc nwxc_init nwxc_input nwxc_is_gga nwxc_is_lda nwxc_is_mgga nwxc_is_on nwxc_print nwxc_print_nwpw nwxc_reset_rho_tolerance nwxc_rtdb_delete nwxc_rtdb_load nwxc_rtdb_store nwxc_vdw3_dftd3 nwxc_wght_hfx nwxc_wght_mp2c raktest rimp2g rism_input rjhtest smd_input task_fragment_energy task_nbo task_rism task_smd task_smd_dynamics task_smd_energy task_smd_fragment uccsdt uccsdtest urand wfn1_input wfn1_task_energy  >> NWCHEM_CONFIG
echo "No extra configuration libraries were added " >> NWCHEM_CONFIG
cp census.skeleton ../stubs.F
for routine in argos argos_input crossing debtest dia_input diana gasdev geninterface jantest jvltest jvltest2 kgdtest leps_energy leps_gradient lucia mc_data mc_driver mc_init mc_main md_data md_driver md_set moints_screen mymc_input mymd_input nbo_input nwxc_eval_df nwxc_eval_df2 nwxc_eval_df3 nwxc_get_cam nwxc_get_disp nwxc_getvals nwxc_getwght nwxc_has_2nd nwxc_has_cam nwxc_has_disp nwxc_has_hfx nwxc_has_mp2c nwxc_has_xc nwxc_init nwxc_input nwxc_is_gga nwxc_is_lda nwxc_is_mgga nwxc_is_on nwxc_print nwxc_print_nwpw nwxc_reset_rho_tolerance nwxc_rtdb_delete nwxc_rtdb_load nwxc_rtdb_store nwxc_vdw3_dftd3 nwxc_wght_hfx nwxc_wght_mp2c raktest rimp2g rism_input rjhtest smd_input task_fragment_energy task_nbo task_rism task_smd task_smd_dynamics task_smd_energy task_smd_fragment uccsdt uccsdtest urand wfn1_input wfn1_task_energy; do \
   sed s/STUBROUTINE/$routine/g stub.skeleton >> ../stubs.F ; \
done
cp util_module_avail_F.begin ../util/util_module_avail.F
echo "c This function was auto generated by make_nwchem_config" >> ../util/util_module_avail.F
for module in NWints analyz atomscf bq cafe ccca ccsd cons cphf dangchang ddscf dimqm dntmc dplot drdy driver esp etrans fcidump fft gradients hessian mcscf mm moints mp2_grad nwdft nwmd nwpw optim perfm prepar property python qhop qmd qmmm rimp2 selci solvation space stepper symmetry tce vib vscf; do \
   echo "        case (\""$module"\")" >> ../util/util_module_avail.F ; \
        done
cat util_module_avail_F.end >> ../util/util_module_avail.F
make[1]: Leaving directory `/home/groups/ruthm/zyzhang/sw/nwchem/src/config'
________________________________

**Comment by edoapra** [comment] 2020-10-06 01:20
```
cd fcidump
make
cd ..
make link
```

**Closed** 2020-12-10 00:52 UTC
