### ISSUE TITLE
Errors while compiling nwchem 6.8 

### ISSUE THREAD

**Issue by Nagavydyanathan** [nwchemgit/nwchem#158] opened 2019-10-10 08:03 UTC
Hi,

I am trying to install nwchem 6.8 with
export NWCHEM_TOP=/home/nvydyanathan/Work/NWChem/nwchem-6.8
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export NWCHEM_MODULES=all
export TCE_CUDA=y
export USE_64TO32=y
export BLAS_SIZE=4
export LAPACK_SIZE=4
export BLASOPT="-lopenblas -lpthread -lrt"

Currently Loaded Modulefiles:
  1) slurm/16.05.0
  2) PrgEnv/GCC+OpenMPI/2018-05-24
  3) cuda/10.1.105
  4) gcc/7.3.0
  5) hwloc/1.11.10
  6) openmpi/2.1.3
  7) GCCcore/5.4.0
  8) binutils/2.26-GCCcore-5.4.0
  9) GCC/5.4.0-2.26
 10) OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1
 11) cuda/9.2.88.1

Compilation: 
cd $NWCHEM_TOP/src
make nwchem_config

cat: /home/nvydyanathan/Work/NWChem/nwchem-6.8/src/tools/build/config.h: No such file or directory
make -C config -f make_nwchem_config NWCHEM_MODULES="all"
grep: /home/nvydyanathan/Work/NWChem/nwchem-6.8/src/tools/build/Makefile: No such file or directory
make[1]: Entering directory `/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/config'
echo \# This configuration generated automatically on \
      `hostname` at `date` > nwchem_config.h
echo "# Request modules from user: all" >> nwchem_config.h
echo "NW_MODULE_SUBDIRS = NWints atomscf ddscf gradients moints nwdft rimp2 stepper driver optim cphf ccsd vib mcscf prepar esp hessian selci dplot mp2_grad qhop property solvation nwpw fft analyz nwmd cafe space drdy vscf qmmm qmd etrans tce bq mm cons perfm dntmc dangchang ccca dimqm" >> nwchem_config.h
echo "NW_MODULE_LIBS = -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm" >> nwchem_config.h
echo "EXCLUDED_SUBDIRS = develop nwxc scfaux rimp2_grad python argos diana uccsdt rism geninterface smd nbo leps lucia rdmft" >> nwchem_config.h
echo "CONFIG_LIBS = " >> nwchem_config.h
echo \# This configuration generated automatically on \
     `hostname` at `date` > NWCHEM_CONFIG
echo "# Request modules from user: all" >> NWCHEM_CONFIG
echo The following subdirectories are built: >> NWCHEM_CONFIG
echo NWints analyz atomscf bq cafe ccca ccsd cons cphf dangchang ddscf dimqm dntmc dplot drdy driver esp etrans fft gradients hessian mcscf mm moints mp2_grad nwdft nwmd nwpw optim perfm prepar property qhop qmd qmmm rimp2 selci solvation space stepper symmetry tce vib vscf >> NWCHEM_CONFIG
echo corresponding to these libraries: >> NWCHEM_CONFIG
echo -lnwints -lanalyze -lguess -lbq -lcafe -lccca -lccsd -lcons -lcphf -ldangchang -lddscf -ldimqm -ldntmc -ldplot -ldrdy -ldriver -lesp -letrans -lpfft -lgradients -lhessian -lmcscf -lmm -lmoints -lmp2 -lnwdft -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -loptim -lperfm -lprepar -lproperty -lqhop -lqmd -lqmmm -lrimp2 -lselci -lsolvation -lspace -lstepper -lnwcutil -ltce -lvib -lvscf >> NWCHEM_CONFIG
echo >> NWCHEM_CONFIG
echo The following directories are excluded from the build: >> NWCHEM_CONFIG
echo develop nwxc scfaux rimp2_grad python argos diana uccsdt rism geninterface smd nbo leps lucia rdmft >> NWCHEM_CONFIG
echo and these routines will be replaced by stubs: >> NWCHEM_CONFIG
echo argos argos_input crossing debtest dia_input diana gasdev geninterface jantest jvltest jvltest2 kgdtest leps_energy leps_gradient lucia mc_data mc_driver mc_init mc_main md_data md_driver md_set moints_screen mymc_input mymd_input nbo_input nwxc_eval_df nwxc_eval_df2 nwxc_eval_df3 nwxc_get_cam nwxc_get_disp nwxc_getvals nwxc_getwght nwxc_has_2nd nwxc_has_cam nwxc_has_disp nwxc_has_hfx nwxc_has_mp2c nwxc_has_xc nwxc_init nwxc_input nwxc_is_gga nwxc_is_lda nwxc_is_mgga nwxc_is_on nwxc_print nwxc_print_nwpw nwxc_reset_rho_tolerance nwxc_rtdb_delete nwxc_rtdb_load nwxc_rtdb_store nwxc_vdw3_dftd3 nwxc_wght_hfx nwxc_wght_mp2c python_input raktest rimp2g rism_input rjhtest smd_input task_fragment_energy task_nbo task_python task_rism task_smd task_smd_dynamics task_smd_energy task_smd_fragment uccsdt uccsdtest urand wfn1_input wfn1_task_energy  >> NWCHEM_CONFIG
echo "No extra configuration libraries were added " >> NWCHEM_CONFIG
cp census.skeleton ../stubs.F
for routine in argos argos_input crossing debtest dia_input diana gasdev geninterface jantest jvltest jvltest2 kgdtest leps_energy leps_gradient lucia mc_data mc_driver mc_init mc_main md_data md_driver md_set moints_screen mymc_input mymd_input nbo_input nwxc_eval_df nwxc_eval_df2 nwxc_eval_df3 nwxc_get_cam nwxc_get_disp nwxc_getvals nwxc_getwght nwxc_has_2nd nwxc_has_cam nwxc_has_disp nwxc_has_hfx nwxc_has_mp2c nwxc_has_xc nwxc_init nwxc_input nwxc_is_gga nwxc_is_lda nwxc_is_mgga nwxc_is_on nwxc_print nwxc_print_nwpw nwxc_reset_rho_tolerance nwxc_rtdb_delete nwxc_rtdb_load nwxc_rtdb_store nwxc_vdw3_dftd3 nwxc_wght_hfx nwxc_wght_mp2c python_input raktest rimp2g rism_input rjhtest smd_input task_fragment_energy task_nbo task_python task_rism task_smd task_smd_dynamics task_smd_energy task_smd_fragment uccsdt uccsdtest urand wfn1_input wfn1_task_energy; do \
   sed s/STUBROUTINE/$routine/g stub.skeleton >> ../stubs.F ; \
done
cp util_module_avail_F.begin ../util/util_module_avail.F
echo "c This function was auto generated by make_nwchem_config" >> ../util/util_module_avail.F
for module in NWints analyz atomscf bq cafe ccca ccsd cons cphf dangchang ddscf dimqm dntmc dplot drdy driver esp etrans fft gradients hessian mcscf mm moints mp2_grad nwdft nwmd nwpw optim perfm prepar property qhop qmd qmmm rimp2 selci solvation space stepper symmetry tce vib vscf; do \
   echo "        case (\""$module"\")" >> ../util/util_module_avail.F ; \
        done
cat util_module_avail_F.end >> ../util/util_module_avail.F
make[1]: Leaving directory `/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/config'

make  >& make.log
[make.log](https://github.com/nwchemgit/nwchem/files/3711197/make.log)

Can you please help resolving the compile error in make.log? 
cc -c -I. -I/cm/extra/apps/OpenMPI/2.1.3/GCC-6.4.0_CUDA-10.0.105_HWLoc-1.11.8/include -I/cm/extra/apps/OpenMPI/2.1.3/GCC-6.4.0_CUDA-10.0.105_HWLoc-1.11.8/lib -I/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/include -I/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/tools/install/include -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DEXT_INT -DLINUX -DLINUX64 -DPARALLEL_DIAG -DNEED_LOC -DSLURM -DTCE_CUDA -DJOBTIMEPATH=\"/home/nvydyanathan/Work/NWChem/nwchem-6.8/bin/LINUX64\" -DNWCHEM_SRCDIR="\"/home/nvydyanathan/Work/NWChem/nwchem-6.8/src\"" -DBYTE_SHORT_PACKING   -DBYTE_SHORT_PACKING    -m64 -Wall -O3 -funroll-loops -ffast-math  -g  -o util_wall_remain.o util_wall_remain.c
util_wall_remain.c:45:25: fatal error: slurm/slurm.h: No such file or directory
 #include <slurm/slurm.h>
                         ^
compilation terminated.

**Comment by jeffhammond** [comment] 2019-10-10 13:53
Did you tell NWChem to build with SLURM support? You might not have done that correctly. 

slurm/slurm.h: No such file or directory #include <slurm/slurm.h>

**Comment by edoapra** [comment] 2019-10-10 16:52
As Jeff mentioned, it is very likely that you have set the environment variable SLURM. If you do not need SLURM support, please do the following
```
unset SLURM
cd $NWCHEM_TOP/src/util
touch util_wall_remain.c
make
cd ..
make 
```

**Comment by Nagavydyanathan** [comment] 2019-10-10 16:55
hi,
yes, you were right. i had slurm module loaded. once unloaded, the compile is proceeding.

thanks,

**Comment by edoapra** [comment] 2019-10-10 16:59
@Nagavydyanathan thanks for the feedback.
If you do need SLURM support, the slurm.h file is provided by the package libslurm-dev (debian/ubuntu) or slurm-devel (redhat/fedora/centos)

**Comment by Nagavydyanathan** [comment] 2019-10-11 05:56
Hi, 
I am getting the following error now, looks like the path is too long and is getting truncated. Is there a way to resolve this?

gfortran: warning: /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39/include: linker input file unused because linking not done
cc -c -I. -I../include -I../ttlg/includes -I/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/include -I/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/tools/install/include -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DEXT_INT -DLINUX -DLINUX64 -DPARALLEL_DIAG /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39/include -DDEBUG_PRINT -m64 -Wall -O3 -funroll-loops -ffast-math  -O1 -o hybrid.o hybrid.c
hybrid.c: In function ‘device_init_’:
hybrid.c:31:3: warning: implicit declaration of function ‘cudaGetDeviceCount’ [-Wimplicit-function-declaration]
   cudaGetDeviceCount(&dev_count_check);
   ^
hybrid.c:38:5: warning: implicit declaration of function ‘cudaSetDevice’ [-Wimplicit-function-declaration]
     cudaSetDevice(device_id);
     ^
cc: warning: /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39/include: linker input file unused because linking not done

**/cm/extra/apps/CUDA.linux86-64/10.1.150_418.39** -c -O3 -Xcompiler -std=c++11 -DNOHTIME -Xptxas --warn-on-spills -arch=sm_35  /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39/include -I/home/nvydyanathan/Work/NWChem/nwchem-6.8/src/tce/ttlg/includes -o memory.o memory.cu
make[3]: execvp: /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39: Permission denied
make[3]: *** [/home/nvydyanathan/Work/NWChem/nwchem-6.8/lib/LINUX64/libtce.a(memory.o)] Error 127

**Comment by Nagavydyanathan** [comment] 2019-10-11 05:57
I have exported the following cuda related flags:
export TCE_CUDA=y
export CUDA=$CUDA_HOME/bin/nvcc
export CUDA_LIBS=$CUDA_HOME/lib64
export CUDA_FLAGS="-arch sm_70"
export CUDA_INCLUDE=$CUDA_HOME/include

CUDA_HOME is - /cm/extra/apps/CUDA.linux86-64/10.1.150_418.39

**Comment by Nagavydyanathan** [comment] 2019-10-11 09:28
Hi,
When I try to run tce_cuda, I get the following error - not sure if this is the right forum to post this.
[nvydyanathan@hsw212 QA]$ ./runtests.mpi.unix procs 2 tce_cuda


 Running tests/tce_cuda/tce_cuda

     cleaning scratch
     copying input and verified output files
     running nwchem (/home/nvydyanathan/Work/NWChem/nwchem-6.8/bin/LINUX64/nwchem)

     NWChem execution failed
H     0.00000000     1.43013023    -0.88554075
end

basis spherical
H library cc-pVDZ
O library cc-pVDZ
end

scf
thresh 1.0e-10
tol2e 1.0e-10
singlet
rhf
end

tce
ccsd(t)
io ga
cuda 1
end

task tce energy
================================================================================


  util_file_name: stub = db
  util_file_name: ltmp, ldir, lname                  255                  255                  255
 ------------------------------------------------------------------------
 util_file_name: name too small                 511
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line :
     0: task tce energy
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error in the input file
 ------------------------------------------------------------------------
 For more information see the NWChem manual at http://www.nwchem-sw.org/index.php/NWChem_Documentation


 For further details see manual section:                                                                                                                                                                                                                                    
[0] Received an Error in Communication: (511) 0:util_file_name: name too small:
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 511.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Failed

**Comment by hjjvandam** [comment] 2019-10-11 17:42
Hi,

Your problem is that the value of

                nw_max_path_len

is too small. You will need to increase that to at least 512 in the file

                nwchem/src/util/util.fh

and recompile. This variable controls the string size for the paths of files. If you run your calculations in a deep directory structure then the path names may get too long for the strings that are meant to store them.

Having said that having a directory name and a prefix that are both 255 characters long seems suspicious to me. You may want to print the contents of the variables “tmp” and “dir” in the subroutine util_file_name0 (util_file_name.F) to see what is actually in them.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by Nagavydyanathan** [comment] 2019-10-15 08:43
Hi,

Thanks for your suggestions. I set the nw_max_path_len to 1024, but this did not help. Following your suggestion, I dumped tmp, dir, name and also their string lengths in util_file_name0 in util_file_name.F as follows:
call util_file_prefix(stub, tmp)
         write(LuOut,*) 'NV:: util_file_name: tmp, dir, name ',
     $        tmp, dir, name
      ltmp = inp_strlen(tmp)
      ldir  = inp_strlen(dir)
         write(LuOut,*) ' NV:: util_file_name: ltmp, ldir, lname',
     $        ltmp, ldir, len(name)

This is the corresponding output dump - the filenames seem ok, but the string lengths are the max array size, and name seems to be empty???

task tce energy
================================================================================


 NV:: util_file_name: tmp, dir, name tce_ccsd_t_h2o.   db                                                                           
  NV:: util_file_name: ltmp, ldir, lname                 1024                 1024                 1024

**Comment by hjjvandam** [comment] 2019-10-15 13:18
Hi,

This is strange. The function inp_strlen [nwchem/src/inp/inp.F] is very simple:

      integer function inp_strlen(a)
      implicit none
#include "inpP.fh"
      character*(*) a !< [Input] The string
      integer i
      logical ois_ws
      intrinsic len
      character*1 xtest
      ois_ws(xtest) = (xtest.eq.xblnk .or. xtest.eq.xtab)
c
      do i = len(a),1,-1
         if (.not. ois_ws(a(i:i))) goto 10
      enddo
c
10   inp_strlen = i
c
      end

I.e. it starts checking the string at the end moving towards the beginning. When it encounters the first non-space, non-tab character it returns the corresponding character index as the length of the string. From what you’re seeing the first character it checks is non-space and non-tab, but from what you see in the printed output there are no printable characters beyond what you would expect. Nevertheless, something seems to think the last character is neither a space nor a tab character. It would seem worthwhile checking what is actually present. Something like int(a(i:i)) should give you the numeric value of the character. The ASCII table from http://www.asciitable.com/ lets you check which characters are present (even if they are non-printable).

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by Nagavydyanathan** [comment] 2019-10-15 18:07
The issue is with these character arrays not being initialized. will this way of computing strlen work always?

**Comment by Nagavydyanathan** [comment] 2019-10-16 14:25
i am using gfortran

**Comment by edoapra** [comment] 2019-10-16 16:33
@Nagavydyanathan what is the output of the pwd command on the directory where you are running these jobs?

**Comment by Nagavydyanathan** [comment] 2019-10-16 17:31
[nvydyanathan@hsw224 src]$ echo $NWCHEM_TOP
/home/nvydyanathan/Work/NWChem/nwchem-6.8

and the tests are run from /home/nvydyanathan/Work/NWChem/nwchem-6.8/QA

Also, when I try to write out the integer value of the last character in tmp using the following line, I get a syntax error:
 write(LuOut,*) ' NV:: util_file_name: tmp ',ichar(tmp(ltmp:ltmp))
                                                                        1
Error: Syntax error in SUBSTRING specification at (1)

**Comment by edoapra** [comment] 2019-10-16 17:45
What version of gfortran are you using, i.e. what is the output of 
```
gfortran -v
```

**Comment by Nagavydyanathan** [comment] 2019-10-16 17:55
[nvydyanathan@psgcluster NWChem]$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/cm/extra/apps/GCC/7.3.0/GCC-4.8.5_GMP-6.1.2_MPFR-4.0.1_MPC-1.1.0/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --enable-shared --enable-threads --with-gmp=/cm/extra/apps/GMP/6.1.2/GCC-4.8.5 --with-mpfr=/cm/extra/apps/MPFR/4.0.1/GCC-4.8.5_GMP-6.1.2 --with-mpfr-lib=/cm/extra/apps/MPFR/4.0.1/GCC-4.8.5_GMP-6.1.2/lib --with-mpc=/cm/extra/apps/MPC/1.1.0/GCC-4.8.5_GMP-6.1.2_MPFR-4.0.1 --prefix=/cm/extra/apps/GCC/7.3.0/GCC-4.8.5_GMP-6.1.2_MPFR-4.0.1_MPC-1.1.0
Thread model: posix
gcc version 7.3.0 (GCC)

**Comment by edoapra** [comment] 2019-10-16 18:01
What command are you using to compile? Could you please re-send the env., variables you are settings.

**Comment by hjjvandam** [comment] 2019-10-16 18:05
Hi,

Hmmm, I am using gfortran 8.2.0 and that works fine (although I typically use an older version of nwchem).

When I try the following code in the printsomething.F:

      program printsomething
      implicit none
      character*(80) tmp
      integer ltmp, luout
      ltmp = 80
      luout = 6
      write(LuOut,*) ' NV:: util_file_name: tmp ',ichar(tmp(ltmp:ltmp))
      end

Note I am using fixed format Fortran. And I compile this code using gfortran:

$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/home/hvandam/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --prefix=/home/hvandam --disable-multilib
Thread model: posix
gcc version 8.2.0 (GCC)

$ gfortran printsomething.F
./a.out
  NV:: util_file_name: tmp            0

Which would suggest that by default the string contains null characters (which might be a problem as inp_strlen checks for characters that are not 9 or 32).

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by hjjvandam** [comment] 2019-10-16 18:15
Hi,

Now a slightly more extended version of printsomething.F:

      program printsomething
      implicit none
      character*(80) tmp
      integer ltmp, luout
      integer, external :: inp_strlen
      ltmp = 80
      luout = 6
      write(LuOut,*) ' NV:: util_file_name: tmp ',ichar(tmp(ltmp:ltmp))
      write(LuOut,*)inp_strlen(tmp)
      tmp = " "
      write(LuOut,*)inp_strlen(tmp)
      end
c
      integer function inp_strlen(a)
      implicit none
      character*1 xblnk         ! Space
      character*1 xtab          ! Tab
      character*(*) a !< [Input] The string
      data xblnk/' '/
      integer i
      logical ois_ws
      intrinsic len
      character*1 xtest
      ois_ws(xtest) = (xtest.eq.xblnk .or. xtest.eq.xtab)
      xtab=char(9)
c
      do i = len(a),1,-1
         if (.not. ois_ws(a(i:i))) goto 10
      enddo
c
10   inp_strlen = i
c
      end

$ gfortran printsomething.F
(py3) -bash-4.1$ ./a.out
  NV:: util_file_name: tmp            0
          80
           0

Which is what I think you are seeing right?

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by hjjvandam** [comment] 2019-10-16 18:33
Hi,

Indeed initialization seems to be important and missing somehow:

      program printsomething
      implicit none
      character*(10) tmp
      integer ltmp, luout, ii
      integer, external :: inp_strlen
      ltmp = len(tmp)
      luout = 6
      write(LuOut,*) ' NV:: util_file_name: tmp ',ichar(tmp(ltmp:ltmp))
      do ii = 1, len(tmp)
        write(LuOut,*)ii,tmp(ii:ii),ichar(tmp(ii:ii))
      enddo
      write(LuOut,*)inp_strlen(tmp)
      tmp = " "
      do ii = 1, len(tmp)
        write(LuOut,*)ii,tmp(ii:ii),ichar(tmp(ii:ii))
      enddo
      write(LuOut,*)inp_strlen(tmp)
      end
c
      integer function inp_strlen(a)
      implicit none
      character*1 xblnk         ! Space
      character*1 xtab          ! Tab
      character*1 xnull         ! Null
      character*(*) a !< [Input] The string
      data xblnk/' '/
      integer i
      logical ois_ws
      intrinsic len
      character*1 xtest
      ois_ws(xtest) = (xtest.eq.xblnk .or. xtest.eq.xtab .or.
     &                 xtest.eq.xnull)
      xtab=char(9)
      xnull=char(0)
c
      do i = len(a),1,-1
         if (.not. ois_ws(a(i:i))) goto 10
      enddo
c
10   inp_strlen = i
c
      end

gfortran printsomething.F
(py3) -bash-4.1$ ./a.out
  NV:: util_file_name: tmp            0
           1            0
           2           16
           3           8
           4 +          43
           5            0
          6            0
           7 ?         216
           8            0
           9            0
          10            0
           7
           1            32
           2            32
           3            32
           4            32
           5            32
           6            32
           7            32
           8            32
           9            32
          10            32
           0

So when I don’t initialize tmp there is some garbage in the string so that even if I check for null characters I still get a length of 7. However, when I initialize the string with a space all characters are set to space and I get the correct length of 0. Interestingly when you printed the string tmp from NWChem it contained sensible information and there was no printable garbage beyond the proper contents. This is strange. If tmp was properly initialized with the intended content I would have expected the remainder of the string to contain only spaces. In that case inp_strlen should have worked. However, in your case the string tmp contained a null character at the end. So where do the null characters that you are seeing come from?

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by Nagavydyanathan** [comment] 2019-10-17 08:25
Hi,

My environment settings are:
Currently Loaded Modulefiles:
  1) cuda/10.1.150
  2) pgi/19.1
  3) GCCcore/5.4.0
  4) binutils/2.26-GCCcore-5.4.0
  5) GCC/5.4.0-2.26
  6) OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1
  7) cuda/10.1.105
  8) PrgEnv/GCC+OpenMPI/2018-05-24
  9) gcc/7.3.0
 10) hwloc/1.11.10
 11) openmpi/2.1.3

export NWCHEM_TOP=/home/nvydyanathan/Work/NWChem/nwchem-6.8
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export NWCHEM_MODULES=all
export TCE_CUDA=y
export CUDA=nvcc
export CUDA_LIBS="-L$CUDA_HOME/lib64 -lcudart -lcublas"
export CUDA_FLAGS="-arch sm_70"
export CUDA_INCLUDE="-I. -I$CUDA_HOME/include"
export USE_64TO32=y
export BLAS_SIZE=4
export LAPACK_SIZE=4
export BLASOPT="-lopenblas -lpthread -lrt"

To compile, I do:
cd $NWCHEM_TOP/src
make realclean
make nwchem_config
make 

To run the test case, I do:
 cd $NWCHEM_TOP/QA
export NWCHEM_EXECUTABLE=$NWCHEM_TOP/bin/LINUX64/nwchem
./runtests.mpi.unix procs 2 tce_cuda

**Comment by Nagavydyanathan** [comment] 2019-10-17 08:27
Also, I tried to dump tmp and dir
NV:: util_file_name: tmp: tce_ccsd_t_h2o.   db   
 NV:: util_file_name: dir:                                                      

dir is actually consisting of non-printable values. Is this expected? and tmp is 'ce_ccsd_t_h2o.   db'
Both inp_strlen is 1024. This, as you said seems to point to initialization issues. I tried setting both tmp and dir to "" at the beginning of the subroutine, but I get similar error.

**Comment by edoapra** [comment] 2019-10-17 18:48
@Nagavydyanathan I have no idea why you are getting this strange behaviour.
Could you try to rebuild without Cuda support?

**Comment by Nagavydyanathan** [comment] 2019-10-22 07:32
@edoapra , @hjjvandam  - Even without cuda support, i get the same error. I believe this is to do with string operations (initialization and concat) in fortran. When i run the tpss test case using ./runtests.mpi.unix procs 2 tpss
I get, tmp with the contents - tmp: tpss.   db
and dir is empty 
In both the strings, there are null characters - looks like the compiler initializes them with null - and hence inp_strlen is computed wrong - it says both tmp and dir are 1024 in length (with is nw_max_path_len) - so it looks like the routines util_file_prefix and util_directory_name, do not put all blanks at the end of the string.
Could you please look into this issue?

thanks,
Naga

**Comment by edoapra** [comment] 2019-10-22 16:54
@Nagavydyanathan nwchem 6.8 has been out for a while (6.8.1 too), and we are in the final stages of preparing 7.0.0. , therefore it does not make any sense to work on 6.8
Could you please download either the master branch or the release-7-0-0 and see if the problem exists there, too?
If the bug show up once again, please send us a detailed report

**Comment by Nagavydyanathan** [comment] 2019-10-23 09:17
@edoapra - I tried with release-7-0-0 and got the same error. Please find make.log attached. My settings are as below:
module purge
module load pgi
module load OpenBLAS
module load openmpi
module unload slurm
export NWCHEM_TOP=/home/nvydyanathan/Work/NWChem/nwchem
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export NWCHEM_MODULES=all
export USE_64TO32=y
export BLAS_SIZE=4
export LAPACK_SIZE=4
export BLASOPT="-lopenblas -lpthread -lrt"
export LARGE_FILES=TRUE
export USE_NOFSCHECK=TRUE
export LAPACK_LIB="-lopenblas"
cd $NWCHEM_TOP/src
make realclean
make nwchem_config
make >& make.log

[make.log](https://github.com/nwchemgit/nwchem/files/3760861/make.log)

The error i get when i run ./runtests.mpi.unix procs 2 tpss is similar to before:
 util_file_name: stub = db
  util_file_name: ltmp, ldir, lname                  255                  255                  255
 ------------------------------------------------------------------------
 util_file_name: name too small                 511
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------

**Comment by edoapra** [comment] 2019-10-23 17:42
The following at the end of your make.log does not look good. This could be the root cause of your problems, since you have two conflicting libgfortran libraries
```
/cm/extra/eb/software/binutils/2.26-GCCcore-5.4.0/bin/ld: warning: libgfortran.so.4, needed by /cm/extra/apps/OpenMPI/2.1.3/GCC-6.4.0_CUDA-10.0.105_HWLoc-1.11.8/lib/libmpi_usempif08.so, may conflict with libgfortran.so.3
/cm/extra/eb/software/binutils/2.26-GCCcore-5.4.0/bin/ld: warning: libgfortran.so.4, needed by /cm/extra/apps/OpenMPI/2.1.3/GCC-6.4.0_CUDA-10.0.105_HWLoc-1.11.8/lib/libmpi_usempif08.so, may conflict with libgfortran.so.3
```

**Comment by ajaypanyala** [comment] 2019-10-23 19:14
@Nagavydyanathan It looks like you have a multiple versions of gcc and openmpi modules loaded which seem to conflict. Could you please try build NWChem by loading a single `gcc` and a compatible `openmpi` module ?

**Comment by Nagavydyanathan** [comment] 2019-10-24 04:18
@edoapra @ajaypanyala  - yes, that seems to have been the problem. It does not throw the strlen error any more.
However, test cases fail - says comparison of outputs failed. This is with release 7-0-0 
Eg: $./runtests.mpi.unix procs 2 tpss


 Running tests/tpss/tpss

     cleaning scratch
     copying input and verified output files
     running nwchem (/home/nvydyanathan/Work/NWChem/nwchem/bin/LINUX64/nwchem)  with 2 processors

     verifying output ... failed
     Comparison of Output Files
@@ -1,4 +0,0 @@
-Effective nuclear repulsion energy (a.u.) 65.41
-Total DFT energy = -193.81899
-Total DFT energy = -193.81899
-Total DFT energy = -193.76629

Failed

**Comment by edoapra** [comment] 2019-10-24 16:39
The test log you show is likely to indicate that your test has produce no real output.
You seem to have skipped one step in your compilation.
After make nwchem_config, you should have executed
```
make 64_to_32
```
then
```
make
```
In order to confirm my theory, could you please upload the file
/home/nvydyanathan/Work/NWChem/nwchem/QA/testoutputs/tpss.out

**Comment by Nagavydyanathan** [comment] 2019-11-04 05:23
@edoapra - sorry for the delay. PFA all the tpss output files



[tpss.ok.out.log](https://github.com/nwchemgit/nwchem/files/3802745/tpss.ok.out.log)
[tpss.ok.out.nwparse.log](https://github.com/nwchemgit/nwchem/files/3802746/tpss.ok.out.nwparse.log)
[tpss.out.log](https://github.com/nwchemgit/nwchem/files/3802747/tpss.out.log)

**Comment by edoapra** [comment] 2019-11-04 17:26
> @edoapra - sorry for the delay. PFA all the tpss output files
> 
> [tpss.ok.out.log](https://github.com/nwchemgit/nwchem/files/3802745/tpss.ok.out.log)
> [tpss.ok.out.nwparse.log](https://github.com/nwchemgit/nwchem/files/3802746/tpss.ok.out.nwparse.log)
> [tpss.out.log](https://github.com/nwchemgit/nwchem/files/3802747/tpss.out.log)

@Nagavydyanathan  Your blas libraries have not been correctly linked. It's likely you have missed the make 64_to_32 step either/or you have not set BLAS_SIZE=4 before any compilation.

**Closed by edoapra** 2019-11-04 17:26 UTC
