### ISSUE TITLE
i386: Compiling basis.F...  f951: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#77] opened 2018-11-08 02:34 UTC
The FreeBSD port fails to build on i386:
> Compiling basis.F...  f951: sorry, unimplemented: 64-bit mode not compiled in

Can some option be specified to fix this?

(I know that i386 isn't a major architecture to run ```NWChem```, but ports are built on all architectures, and it would be nice if ```NWChem``` would build successfully.)

**Comment by hjjvandam** [comment] 2018-11-08 15:53
Hi Yuri,

Is the i386 a 32-bit or 64-bit machine. I.e. does it use 32-bit addresses or 64-bit addresses? It seems as if the machine uses 64-bit addresses but the Fortran compiler you are using does not support Integer*8?
Knowing what exactly an “i386” machine is well help in determining how this problem can be solved.

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by jeffhammond** [comment] 2018-11-08 17:09
@hjjvandam i[3456]86 are ILP32 platforms, i.e. they have 32-bit `int`, `long`, and pointers.  There is no reason why this can't support NWChem, and it certainly did in the past.

The only issue with ILP32, which does not matter here, is that one cannot index 1D global arrays larger than 2 gigawords, which was a major issue for TCE on Blue Gene/P.

**Comment by jeffhammond** [comment] 2018-11-08 17:10
@yurivict How is this compiled?  Why would `NWCHEM_TARGET=LINUX` require the Fortran compiler to support 64-bit?

**Comment by yurivict** [comment] 2018-11-08 17:13
This is compiled from the port ```science/nwchem```.
https://svnweb.freebsd.org/ports/head/science/nwchem/Makefile?revision=484428&view=markup

**Comment by jeffhammond** [comment] 2018-11-08 17:42
`NWCHEM_TARGET=LINUX64` is for 64-bit platforms.  Use `NWCHEM_TARGET=LINUX` for 32-bit platforms.

Closing the issue because it is not an NWChem problem.

**Closed by jeffhammond** 2018-11-08 17:42 UTC

**Comment by yurivict** [comment] 2018-11-10 01:49
I replaced ```NWCHEM_TARGET=LIBUX``` and now it breaks in a different way: http://beefy10.nyi.freebsd.org/data/112i386-default/484565/logs/nwchem-6.8.1.20181107.log

**Comment by jeffhammond** [comment] 2018-11-10 02:06
The problem is pretty obvious.  Do you not need read the logs before reporting github issues?
“perl: Command not found.”
