### ISSUE TITLE
Compilation error with GCC/12.2: 'pslans' at (1) has no IMPLICIT type

### ISSUE THREAD

**Issue by dipietrantonio** [nwchemgit/nwchem#815] opened 2023-06-29 05:22 UTC
**Describe the bug**
I get the following compilation error while compiling nwchem 7.2.0:
```
Compiling D3dBs-new.F...
D3dBs-new.F:500:30:

  500 |         call fftw_execute_dft(pslans(1,nb),A(indx),A(indx))
      |                              1
Error: Function 'pslans' at (1) has no IMPLICIT type
```
I also get several other worrying warnings:

```
inp.F:1370:37:

 1369 |       do i = 1, 3*max_width+80+6
      |                                                                        2
 1370 |          csave(i,save_level) = cdata(i)
      |                                     1
Warning: Array reference at (1) out of bounds (3158 > 1) in loop beginning at (2)
```
**Describe settings used**
I am trying to compile nwchem using spack/0.19.0 on a Cray EX supercomputer. We are using the `gcc/gfortran 12.2.0` compilers and `fftw/3.3.9`.
[nwchem.txt](https://github.com/nwchemgit/nwchem/files/11902162/nwchem.txt)

Let me know if you need more information.

**Comment by edoapra** [comment] 2023-06-29 17:05
Duplicate of https://github.com/nwchemgit/nwchem/issues/792

**Comment by edoapra** [comment] 2023-06-29 17:07
If you are using spack, you might want to have a look at
https://github.com/nwchemgit/nwchem/issues/792

**Closed** 2023-07-02 01:02 UTC
Labels: duplicate
