### ISSUE TITLE
Installation of nwchem-v6.8 on an HPC cluster does not understand what `loff_t` is

### ISSUE THREAD

**Issue by hawiki** [nwchemgit/nwchem#833] opened 2023-07-14 02:21 UTC
**Describe the bug**
Installation of nwchem-v6.8 on an HPC cluster does not understand what `loff_t` is.

**Settings**
```
export NWCHEM_TOP=$(pwd)
export NWCHEM_TARGET=LINUX64
export NWCHEM_EXECUTABLE="$NWCHEM_TOP/bin/LINUX64/nwchem"
export USE_MPI=y
export MPI_F90=mpif90
export MPI_CC=mpicc
export MPI_CXX=mpicxx
export NWCHEM_MODULES="smallqm nwxc"
export FC="ifort"
export BLASOPT="${MKLROOT}/lib/intel64/libmkl_blas95_ilp64.a ${MKLROOT}/lib/intel64/libmkl_lapack95_ilp64.a -L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64  -lmkl_sequential -lmkl_core -lmkl_blacs_openmpi_ilp64 -lpthread -lm -ldl  -I${MKLROOT}/include/intel64/ilp64 -i8 -I'${MKLROOT}/include'"
export USE_64TO32=y
export BLAS_SIZE=4
```
Fortran compiler ifort and C compiler icc.
MPI implementation OpenMPI 3.1.6.

**Attach log files**
I run this script `contrib/distro-tools/build_nwchem` to install, but before that, all of the above variables have been set and this intel script `/opt/intel/oneAPI/setvars.sh` has also been run because the MKL is from Intel oneAPI. The error is 
```
mpicc -c -I. -I/opt/apps/mpi/openmpi-3.1.6_intel-2021.4.0/include -I/opt/apps/mpi/openmpi-3.1.6_intel-2021.4.0/lib -I/home/iwahyutama/Programs/NWChem/NWChem-WFAT-6.8/src/include -I/home/iwahyutama/Programs/NWChem/NWChem-WFAT-6.8/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DPARALLEL_DIAG -DNEED_LOC -DSLURM -DSLURM -DNOFSCHECK -DJOBTIMEPATH=\"/home/iwahyutama/Programs/NWChem/NWChem-WFAT-6.8/bin/LINUX64\" -DNWCHEM_LONG_PATHS -DNWCHEM_SRCDIR="\"/home/iwahyutama/Programs/NWChem/NWChem-WFAT-6.8/src\"" -DBYTE_SHORT_PACKING   -DBYTE_SHORT_PACKING    -g  -o util_fadvise.o util_fadvise.c`
util_fadvise.c(47): error: identifier "loff_t" is undefined
      loff_t offset = 0;
      ^
util_fadvise.c(48): error: identifier "loff_t" is undefined
      loff_t length = fd_stat.st_size;
```
I think `loff_t` is supposed to be provided by `sys/types.h`.

**Additional context**
Apart from the above error, I wonder why is the install script `contrib/distro-tools/build_nwchem` never referred to in the NWChem'sinstallation manual? The error above happened when I installed NWChem from source on a new machine, but I have always used that script on another HPC machine I have always worked on. So, this script is actually working.

**Comment by edoapra** [comment] 2023-07-14 02:31
Duplicate of https://github.com/nwchemgit/nwchem/issues/41

Please use the latest NWChem release 7.2.0 that contains this fix.

https://github.com/nwchemgit/nwchem/releases/tag/v7.2.0-release

**Closed by edoapra** 2023-07-14 02:31 UTC

**Comment by hawiki** [comment] 2023-07-14 02:45
Thanks, so it's basically replacing loff_t with off_t.

Can you please comment on my last question in the Additional Context? Is there a pitfall of using `contrib/distro-tools/build_nwchem` such that it's never suggested in the manual?

**Comment by edoapra** [comment] 2023-07-14 02:52
NWChem is an open-source project and everybody is welcome to contribute.
If would like to describe successful use of the script you mention and mention it in the manual available at the site https://nwchemgit.github.io, please do so.
