### ISSUE TITLE
optimization with constraints NWCHEM 6.6

### ISSUE THREAD

**Issue by moondog7** [nwchemgit/nwchem#39] opened 2018-05-05 12:52 UTC
Hi ,

I would running a optimization with constraints, but I obtain this message error

"input error at line 711: at end of line looking for integer range

fix atom 173 174:698

------------------------------------------------------------------------

 current input line :

  711: fix atom 173 174:698"

regards

M

I append my input

start visudyne01_on_MSN_opt
memory 1800 MW
scratch_dir /tmp/tmp_nwchem

title "visudyne01_on_MSN_opt basis set cc-pVDZ for molecule / support lanl2dz"
charge 0

geometry units angstroms print xyz autosym
C 17.87160 27.05140 27.35170
C 17.27960 25.75670 26.73920
C 17.37810 24.58450 27.75480
C 18.56500 29.35930 26.81850
C 15.37050 36.71100 23.99170
C 14.97670 38.13060 23.80270
C 15.75750 39.15920 24.14040
C 17.57330 40.35780 24.75660
C 18.80420 40.67150 25.16150
C 19.64810 39.70610 25.90980
C 20.37230 37.91060 26.88090
C 20.59000 36.62220 27.18790
C 19.89790 35.44020 26.78720
C 18.29420 34.13640 25.83090
C 17.13580 33.92170 25.02670
C 16.30920 34.85110 24.50790
C 15.17260 34.56390 23.64220
C 14.54620 35.69940 23.30490
C 15.50090 40.57850 23.83920
C 16.60460 41.30010 24.16720
C 20.94350 40.21580 26.52260
C 21.19650 39.00260 27.38240
C 20.22710 34.11160 27.01970
C 19.19520 33.26500 26.44690
C 14.18750 41.05960 23.31950
C 16.73760 42.74260 24.10920
C 16.50040 43.49990 23.03070
C 13.36340 35.95150 22.44860
C 14.79120 33.20390 23.13920
C 13.79870 32.51180 24.06740
C 13.13660 31.36310 23.35180
C 21.45820 33.65210 27.73790
C 19.30860 31.74560 26.54120
C 18.14280 30.76620 26.31860
C 20.90130 41.51440 27.36690
C 21.91170 39.08570 28.51810
C 22.46190 40.36160 28.94230
C 21.97140 41.51770 28.45120
C 19.53640 41.82200 27.97400
C 22.43110 42.85920 28.89640
C 22.00960 40.32000 25.41350
C 23.94560 44.04350 30.21700
C 17.94190 41.22120 29.57730
C 12.53780 29.11060 23.50130
O 19.62940 29.17810 27.41080
O 12.61490 31.45110 22.24830
O 13.17790 30.23430 24.11100
O 21.93800 43.89250 28.48140
O 18.77620 42.66580 27.51090
O 23.45540 42.77330 29.78190
O 19.24880 41.02500 29.03650
N 17.67940 28.30370 26.60050
N 16.37160 36.22470 24.67340
N 16.96340 39.13970 24.76750
N 19.39740 38.43450 26.06560
N 18.72500 35.43700 26.07520
H 18.94530 26.89610 27.51020
H 17.42520 27.22740 28.33750
H 17.82000 25.51340 25.81660
H 16.23180 25.91870 26.46000
H 16.69560 24.79520 28.58710
H 18.39100 24.56220 28.17580
H 17.45480 38.28440 25.01340
H 18.24320 36.26670 25.74550
H 14.03690 40.72510 22.28810
H 13.36580 40.67610 23.93390
H 14.10050 42.14940 23.33270
H 17.10190 43.21850 25.01950
H 16.17160 43.07370 22.08870
H 16.64600 44.57500 23.07130
H 12.58070 36.46530 23.01610
H 13.63520 36.57190 21.58840
H 12.92410 35.02790 22.06240
H 15.67510 32.57270 22.98880
H 14.36560 33.30300 22.13240
H 14.31520 32.15180 24.96450
H 13.00210 33.18950 24.39670
H 22.33970 34.18760 27.36850
H 21.36060 33.84410 28.81120
H 21.65380 32.58660 27.59580
H 20.13050 31.44800 25.87460
H 19.66680 31.56240 27.56420
H 17.25960 31.08170 26.88330
H 17.88570 30.70510 25.25670
H 21.10640 42.35310 26.68510
H 22.03480 38.24320 29.19170
H 23.22120 40.33650 29.71970
H 22.05090 39.41500 24.79560
H 21.78850 41.15470 24.73770
H 23.01100 40.48420 25.82730
H 24.78500 43.86940 30.89580
H 24.30650 44.63050 29.36610
H 23.16700 44.58840 30.76030
H 17.17770 41.04510 28.81360
H 17.79740 40.49770 30.38410
H 17.85010 42.22920 29.99370
H 19.18180 41.68030 25.04630
H 14.04350 38.32140 23.29140
H 21.44020 36.42430 27.83630
H 16.93540 32.88120 24.80290
H 12.60760 28.26620 24.19180
H 11.47950 29.32320 23.31830
H 13.04620 28.84120 22.57010
H 16.74220 28.53450 26.29880
Si 17.01470 22.77140 27.20570
Si 11.90480 17.79180 23.96230
Si 14.93880 20.75800 21.07710
Si 12.68230 19.76990 19.10390
Si 13.98430 23.69650 21.56230
Si 15.86260 19.72780 23.88970
Si 9.95440 21.21860 22.37080
Si 11.80830 17.40980 20.86760
Si 10.89510 24.04450 21.70010
Si 10.52680 25.03240 24.60680
Si 17.08430 16.93760 23.90200
Si 17.04560 20.15660 28.76480
Si 14.04110 22.18630 26.41910
Si 11.90950 20.79180 24.68510
Si 12.36220 24.70950 27.05180
Si 14.80170 19.29390 26.86960
O 11.68270 18.59850 19.71830
O 16.26570 20.31950 20.21040
O 11.37640 21.04070 23.15520
O 13.55830 20.29510 20.36640
O 14.22870 24.04290 23.15700
O 16.74850 18.45310 23.41500
O 10.19150 24.96060 20.53590
O 14.53200 25.00970 20.72040
O 14.91310 22.41220 21.13510
O 14.91180 20.16020 22.62240
O 12.09880 18.02320 22.35650
O 15.79320 16.27160 24.69530
O 10.98980 25.00040 23.03400
O 9.85550 26.51020 24.90980
O 9.86080 22.78940 21.94560
O 11.88710 21.06020 18.44600
O 13.02680 16.37980 20.43120
O 8.69440 20.79710 23.34360
O 16.86630 20.99090 24.19870
O 12.90130 16.59460 24.50470
O 12.38590 23.51210 21.23960
O 9.82800 20.26480 21.04500
O 10.36390 17.31940 24.32500
O 10.40450 16.54390 20.86690
O 16.81340 19.62340 30.30030
O 13.81920 18.04000 27.30290
O 10.77980 21.26280 25.74680
O 13.31330 25.99670 27.46280
O 15.64640 22.67960 26.19530
O 15.03770 19.25330 25.23280
O 16.68240 21.77530 28.53570
O 13.25340 21.76130 24.99950
O 12.22750 19.17600 24.81070
O 11.90980 24.88660 25.48500
O 14.09070 20.74700 27.25100
O 9.45230 23.84200 24.90200
O 10.98650 24.74260 27.92270
O 16.19850 19.19250 27.72170
O 13.18730 23.30950 27.26260
O 18.39840 22.06330 26.49890
H 13.87660 24.90410 23.42640
H 14.75270 24.81030 19.79760
H 15.69490 15.31730 24.54530
H 9.10290 26.73740 24.34040
H 12.87160 15.95530 19.57410
H 7.98710 21.46740 23.38220
H 16.42090 21.85100 24.28710
H 13.81730 16.87370 24.68100
H 9.49240 20.70110 20.24120
H 10.34240 16.67550 25.05100
H 9.65710 17.04340 21.23090
H 12.87650 26.85440 27.35250
H 7.63320 26.52140 11.40720
H 10.02750 19.24620 10.68510
H 7.06200 21.42620 11.17590
H 14.82290 19.41100 10.35680
H 15.57340 14.45940 13.36440
H 11.57250 23.22580 9.94250
H 9.70650 26.28590 10.51340
H 17.87850 20.10490 12.02180
H 27.83260 18.63580 11.36300
H 24.91730 15.41260 11.02430
H 20.19290 14.63760 12.03640
H 16.65870 14.76500 10.14450
H 25.09510 20.30710 11.26630
H 21.62990 20.49340 10.36900
H 15.74560 17.44360 42.17740
H 11.96300 15.62180 39.30980
H 10.55500 21.17210 40.60070
H 16.61750 21.01970 41.02160
H 10.77090 18.62450 40.98240
H 13.13830 16.75550 42.75980
H 20.69500 13.95310 41.74230
H 22.82910 18.26930 40.64040
H 17.98790 14.01790 39.25490
H 18.49080 16.56650 41.81280
H 22.51290 21.83460 41.29090
H 5.54260 28.94190 12.98550
H 14.16710 16.07560 16.13940
H 6.85640 21.33300 20.56050
H 6.39630 23.13070 17.45310
H 12.51290 26.48950 14.28120
H 15.19420 23.23100 12.42440
H 16.73360 14.87680 20.07630
H 6.29000 22.30300 25.04610
H 2.65690 28.03490 17.50090
H 7.95240 19.07170 14.53950
H 4.15160 24.15180 12.29370
H 19.39870 21.04220 17.19490
H 11.28710 18.26060 16.17220
H 8.39080 21.37780 17.96370
H 2.99260 22.99010 23.18820
H 13.05490 18.39190 11.69180
H 2.83690 25.24290 22.21770
H 5.89800 29.16150 15.55440
H 4.85040 23.92510 15.80910
H 8.66230 29.76690 19.98230
H 8.04400 27.02250 15.02400
H 10.55200 28.76400 16.72820
H 2.76310 24.35720 17.25720
H 28.76120 20.88770 19.35970
H 25.16340 15.15750 18.78970
H 29.72520 19.92600 14.89790
H 27.83830 16.67680 14.34140
H 22.40010 15.73970 12.80440
H 20.90610 17.07140 23.77600
H 26.77390 22.33540 15.25520
H 22.80180 19.88130 21.36560
H 20.32200 19.55390 18.91500
H 26.57730 14.71950 15.47510
H 25.40860 14.88270 21.80200
H 20.42750 14.14470 18.38150
H 19.99330 20.43280 12.68700
H 21.88820 14.17340 20.34110
H 27.64720 19.90350 17.69560
H 18.79420 20.56320 20.73970
H 27.10580 22.03310 21.73300
H 27.70790 15.96060 21.06350
H 27.68020 17.67160 17.69210
H 30.00980 16.49850 23.19050
H 17.73060 15.13320 17.76990
H 8.02080 23.52650 15.73880
H 23.00620 21.96980 16.31110
H 24.60460 21.47510 23.08650
H 21.54350 19.38540 23.27820
H 5.28340 30.19430 20.32790
H 13.11040 15.40970 28.71640
H 6.32190 21.69590 32.93470
H 14.70440 23.17970 35.24920
H 6.63410 23.34460 29.77450
H 4.66820 29.32000 24.48080
H 2.93180 26.30490 24.60780
H 17.41630 15.62870 31.34890
H 5.87690 22.97420 36.70020
H 3.44240 29.45700 30.74980
H 14.60430 23.95680 31.95900
H 8.80920 19.29700 26.08700
H 10.70870 17.97350 27.76710
H 8.40180 21.78380 30.31610
H 2.55760 23.39370 35.79280
H 2.79760 24.85850 34.06810
H 16.89980 14.34270 34.58040
H 6.66370 30.35960 28.69320
H 4.54260 25.10470 28.46550
H 7.75060 31.27110 33.16570
H 7.00680 28.94690 26.68100
H 9.65600 26.61570 36.97280
H 11.48240 28.39930 31.32360
H 12.33860 15.76020 31.84810
H 7.39550 21.35910 35.75590
H 16.22290 20.33480 35.95550
H 13.05380 16.14290 36.64720
H 9.02260 20.51360 32.20960
H 2.39070 26.53030 28.88430
H 28.90440 20.21890 31.73130
H 25.04070 15.96880 31.08000
H 22.87000 16.31130 26.17780
H 21.77590 16.58870 36.94300
H 28.04040 22.06070 25.59010
H 23.97530 21.58430 33.47070
H 21.19720 20.75160 30.58180
H 25.54360 16.00760 27.31850
H 25.04040 15.25050 33.74750
H 21.07460 15.00530 29.29780
H 22.84920 15.53870 30.81450
H 27.90630 21.32440 29.05340
H 19.18610 20.85240 31.38190
H 27.87820 22.03600 34.67770
H 28.91740 16.72570 33.29300
H 30.27260 18.55660 30.98460
H 29.00900 15.22770 30.83970
H 30.53120 18.72860 35.88890
H 17.77500 16.30500 27.72830
H 31.40080 17.97210 26.07210
H 1.82040 23.23070 26.47950
H 9.16240 16.35120 35.37480
H 8.30990 25.04620 28.45860
H 8.84290 17.91460 32.95530
H 23.49910 23.33890 27.35440
H 24.46310 22.28130 36.52330
H 20.94530 21.44870 35.42910
H 6.14920 29.88780 37.14830
H 2.56300 27.10430 38.03640
H 13.04430 25.70950 39.55570
H 15.84650 22.27690 37.21440
H 8.58420 18.51670 38.60230
H 4.69070 24.46630 40.91190
H 8.65560 28.06300 38.27640
H 12.52510 22.68050 41.42090
H 26.83170 16.39090 38.43640
H 23.32970 17.65110 38.33280
H 19.08870 21.13090 37.59230
H 27.62340 19.79710 39.23610
H 0.83510 24.48560 38.13370
H 4.22850 30.44000 33.21060
Si1 16.13830 18.72150 11.98210
Si1 10.21660 24.31090 11.33930
Si1 16.90710 15.73130 12.13100
Si1 16.74760 18.81480 40.75550
Si1 12.53530 17.26790 40.70240
Si1 9.15910 20.65550 38.94840
Si1 14.39810 18.81880 38.76580
Si1 19.50310 15.20810 40.36830
Si1 19.29730 19.58020 39.15050
Si1 22.26020 20.22250 39.77240
Si1 22.62630 21.04870 36.81420
Si1 19.70350 16.84540 37.74110
Si1 6.64310 27.05610 13.31080
Si1 8.70740 25.61740 20.27710
Si1 10.59860 21.56860 17.55680
Si1 6.37160 28.00030 17.40140
Si1 17.62320 19.81510 16.65180
Si1 5.78990 24.14620 13.80320
Si1 6.66030 23.35180 19.66350
Si1 17.36150 19.20720 19.71010
Si1 3.90750 26.19600 17.73460
Si1 9.31620 27.18770 17.72940
Si1 4.41730 25.24660 20.64650
Si1 9.93440 24.41140 16.48780
Si1 13.51390 21.97220 13.16490
Si1 6.61980 26.90020 22.18810
Si1 13.47180 18.12290 16.63070
Si1 11.43880 19.79490 12.30740
Si1 6.47260 29.32230 20.24380
Si1 11.79480 24.39430 14.00290
Si1 8.20940 22.43650 12.79520
Si1 9.64820 20.50900 14.76720
Si1 15.17460 19.82400 14.72240
Si1 24.16260 17.03320 12.33250
Si1 23.97300 18.34200 17.02220
Si1 26.80020 18.34270 13.30150
Si1 17.97250 16.42990 21.06000
Si1 19.64620 15.35680 16.66550
Si1 27.63230 20.31080 15.53590
Si1 19.68030 19.06280 14.41530
Si1 21.14550 17.68680 18.04050
Si1 26.18020 16.17010 17.08150
Si1 22.53860 20.22600 15.01270
Si1 21.04950 16.20390 20.73900
Si1 23.90090 16.50850 21.76560
Si1 27.28070 20.03760 20.76370
Si1 28.24510 17.61910 22.41520
Si1 24.42070 19.05950 20.02140
Si1 23.01430 19.88960 11.98250
Si1 19.57520 16.04260 13.64840
Si1 8.62500 25.61450 33.18240
Si1 10.62650 21.62570 30.01450
Si1 6.00480 27.67940 25.13220
Si1 6.95760 28.49710 29.88170
Si1 3.25950 24.15020 25.07020
Si1 5.78890 25.00210 26.63310
Si1 11.16350 17.12410 35.99490
Si1 6.51390 23.68310 31.96040
Si1 17.35140 19.71570 31.85010
Si1 14.54240 19.79360 33.25840
Si1 4.04260 27.44340 30.05770
Si1 9.63760 27.26660 30.80180
Si1 4.23780 25.69430 32.57470
Si1 12.33740 19.27900 31.10470
Si1 10.29590 24.61290 29.38680
Si1 6.28190 27.12370 34.47810
Si1 13.49500 22.74460 33.44980
Si1 12.78890 17.58480 28.49850
Si1 15.31800 18.28960 35.86950
Si1 9.14840 20.83690 34.42850
Si1 6.24770 29.70080 32.67470
Si1 10.91400 17.13160 32.89930
Si1 10.58410 23.54850 34.36080
Si1 10.25780 24.49250 37.27780
Si1 8.17960 23.27980 25.76290
Si1 9.83480 21.03180 27.04070
Si1 17.48220 16.16490 35.72030
Si1 24.34090 17.25330 24.76080
Si1 23.78390 19.52830 29.00260
Si1 27.24170 18.04350 25.34340
Si1 18.40140 16.91140 32.88900
Si1 19.97970 16.52540 28.06450
Si1 28.11900 20.38270 27.04150
Si1 19.32320 20.69410 26.88050
Si1 21.04400 18.60770 30.01240
Si1 25.66550 17.08660 29.27590
Si1 22.39890 21.44350 26.93800
Si1 21.40630 16.52650 32.21630
Si1 24.04060 17.22720 33.52550
Si1 27.31330 20.44700 33.24940
Si1 28.58350 18.20700 34.95050
Si1 24.49890 19.96090 32.02580
Si1 29.53980 17.74600 27.29230
Si1 28.60700 17.32350 30.20270
Si1 23.34540 20.13280 24.32180
Si1 19.62700 17.96360 25.36260
Si1 6.61040 27.73400 37.51900
Si1 2.81910 25.02350 37.27680
Si1 5.40660 25.25520 38.95320
Si1 13.77600 21.57500 37.61230
Si1 11.18630 20.12110 36.62040
Si1 12.31940 23.60890 39.42100
Si1 7.57830 23.20520 38.13890
Si1 24.14720 18.39940 36.40180
Si1 26.99230 18.44820 37.59560
O1 6.87850 27.07570 11.68710
O1 10.42590 20.05960 11.02900
O1 16.76840 17.26530 11.59010
O1 7.36500 21.21590 12.07230
O1 14.70370 18.90460 11.17780
O1 15.47110 15.17530 12.71860
O1 11.00490 24.01280 9.92060
O1 9.23820 25.61620 11.03940
O1 17.13210 19.91200 11.42310
O1 27.06720 19.01970 11.81890
O1 24.73800 16.36070 10.94010
O1 20.59020 15.39590 12.49490
O1 17.30710 14.74910 10.86430
O1 24.18430 20.56140 11.03740
O1 21.55360 20.31230 11.31970
O1 16.66350 17.63370 41.91050
O1 13.07070 18.30920 39.57730
O1 12.49300 15.73670 40.11570
O1 10.01000 20.40170 40.34790
O1 16.24080 20.22840 41.43380
O1 11.01650 17.69780 41.16190
O1 13.50250 17.29390 42.03950
O1 15.79250 18.38320 39.50400
O1 20.51690 13.98180 40.79100
O1 20.11580 16.00400 39.08510
O1 18.30340 18.96700 40.29280
O1 22.86730 18.68140 39.75990
O1 20.63320 20.18430 39.89860
O1 22.76610 21.04170 38.44680
O1 18.02550 14.57380 40.04840
O1 19.38310 16.19610 41.67670
O1 22.87650 20.95390 41.11650
O1 5.90900 28.46920 13.75100
O1 17.34390 18.99100 18.06710
O1 6.72250 26.95380 23.84350
O1 13.88650 18.97580 15.29780
O1 8.98480 26.92530 19.31570
O1 14.40730 16.77230 16.76830
O1 7.15960 22.23310 20.75900
O1 10.56120 19.70240 13.67810
O1 6.53720 22.54870 18.22330
O1 10.58620 20.84270 16.08120
O1 5.71270 25.78630 13.76020
O1 12.80470 25.59650 14.51280
O1 6.30660 28.29020 18.99930
O1 14.34300 22.91540 12.08230
O1 10.63570 23.22050 17.39050
O1 5.28800 26.80080 17.08030
O1 17.65020 15.19110 20.00760
O1 7.17390 22.50200 24.69410
O1 2.61860 27.09980 17.24950
O1 15.93930 18.90810 13.59140
O1 10.15440 25.93480 17.07390
O1 5.26220 26.07630 21.77870
O1 8.44530 19.48950 15.26300
O1 4.51630 23.54320 12.95350
O1 6.58420 28.45190 21.63660
O1 18.45490 21.20010 17.01950
O1 7.98390 26.12690 21.66760
O1 11.92340 17.58730 16.45650
O1 8.94840 21.86700 14.15590
O1 7.88740 27.49270 16.93680
O1 9.23240 21.16420 18.40560
O1 3.02810 22.81270 24.14370
O1 12.58750 20.94710 12.29780
O1 12.13380 18.33080 12.01080
O1 3.02930 24.73890 21.40410
O1 7.73610 24.56340 19.48410
O1 5.20000 23.90780 20.12820
O1 5.94730 29.32330 16.51620
O1 11.33100 24.72800 12.46360
O1 14.64630 21.23250 14.07250
O1 5.67190 23.63230 15.36820
O1 7.82380 30.24830 20.06770
O1 13.63020 19.05810 17.96560
O1 9.33400 22.99120 11.73390
O1 8.10590 27.00710 14.05550
O1 10.45630 24.36910 14.94120
O1 16.19640 20.22240 15.94930
O1 12.57110 22.95020 14.08790
O1 3.97530 26.18890 19.37430
O1 10.23730 28.55630 17.61980
O1 7.20130 23.66160 13.15980
O1 3.67350 24.67250 17.13000
O1 27.85300 20.54730 19.29730
O1 19.73500 17.66670 13.55780
O1 27.61260 18.25110 23.77000
O1 24.56150 16.98610 23.17040
O1 25.44320 14.94420 17.88610
O1 23.14200 18.26180 11.98610
O1 29.12790 20.68590 14.96990
O1 28.04600 17.31300 13.62900
O1 23.32930 15.83000 13.08970
O1 20.69590 17.96840 24.09070
O1 26.88430 21.70570 15.98260
O1 24.53330 19.09420 18.38050
O1 23.01730 19.83930 20.41570
O1 22.56940 17.52330 17.25530
O1 20.69370 19.28070 18.05400
O1 27.00410 15.52940 15.79960
O1 22.25220 16.35590 21.86800
O1 24.36650 17.50580 20.54700
O1 24.53320 15.01780 21.39920
O1 20.49550 14.15600 17.41070
O1 25.11750 17.27010 16.52330
O1 20.04380 15.41620 15.08310
O1 19.27150 20.24260 13.31870
O1 19.58110 16.57560 21.34390
O1 18.54000 18.93860 15.59880
O1 21.07280 14.66420 20.14050
O1 28.06910 18.66260 21.16560
O1 17.34240 16.03180 22.54490
O1 23.74510 19.46680 15.83660
O1 25.65570 19.88200 20.71950
O1 27.81510 19.38060 16.88470
O1 18.85930 19.82850 20.10700
O1 25.40810 17.49070 13.28300
O1 26.74480 19.53920 14.41150
O1 27.66660 21.24860 21.81740
O1 27.51810 16.19650 21.98810
O1 21.16450 19.34380 15.03480
O1 21.39260 17.27740 19.58310
O1 17.21660 17.77820 20.50360
O1 27.26780 16.88120 18.09180
O1 18.04400 15.58040 13.29270
O1 23.06990 20.52600 13.48800
O1 29.84220 17.28230 22.64600
O1 18.04590 15.00320 16.86020
O1 19.94620 16.78620 17.39700
O1 8.30540 24.12440 16.44890
O1 22.26240 21.67290 15.76630
O1 24.74450 20.75710 23.72090
O1 22.34080 19.89740 23.02650
O1 11.21670 18.37290 31.88010
O1 5.96200 27.40050 36.06510
O1 9.07750 26.93480 32.30610
O1 13.33900 16.20690 29.21920
O1 6.24100 22.62900 33.19320
O1 16.13720 20.03930 32.91260
O1 10.49180 20.25300 35.13940
O1 13.76190 19.24040 31.92420
O1 14.30800 23.69750 34.52600
O1 6.70620 22.79390 30.57760
O1 4.57610 28.37620 24.68760
O1 10.69540 21.17180 28.43420
O1 5.70940 26.61440 26.34510
O1 2.96180 25.46320 24.11950
O1 6.91490 29.48040 31.19480
O1 10.82060 23.26280 30.16560
O1 15.95920 16.78060 35.75950
O1 5.66320 27.49520 29.82860
O1 17.22160 15.94290 32.24560
O1 6.67640 22.48280 36.94940
O1 3.37970 28.94450 29.92400
O1 10.00640 24.98860 33.81280
O1 10.52650 26.00560 30.22910
O1 14.10690 23.12660 31.96590
O1 4.94810 26.40030 33.86430
O1 9.17890 19.51770 26.95950
O1 4.79200 24.16590 25.63420
O1 6.63970 28.54780 33.75220
O1 7.58760 26.11550 34.36490
O1 13.82640 21.17780 33.80590
O1 14.47150 18.67200 34.49560
O1 11.32470 17.22270 27.82550
O1 8.65220 22.18720 26.92010
O1 8.35800 27.62520 29.82750
O1 9.14250 21.24280 30.65400
O1 2.64060 24.36180 35.77630
O1 11.55110 17.32920 34.40540
O1 2.92440 24.84280 33.10030
O1 7.89290 24.52430 32.20370
O1 5.24660 24.68860 31.77320
O1 17.37330 14.54630 35.40130
O1 6.91900 29.44070 28.51300
O1 5.38080 24.67800 28.20130
O1 6.79360 31.14410 33.26090
O1 12.60170 18.77110 29.57810
O1 6.97400 28.87950 25.70680
O1 10.91270 23.71520 35.97630
O1 10.48540 26.12080 37.11160
O1 9.37690 22.43190 34.15110
O1 3.69770 26.85870 31.54620
O1 11.75930 20.82960 30.93340
O1 10.63210 28.58500 30.89730
O1 7.34820 24.51470 26.44670
O1 11.45460 15.72130 32.24320
O1 7.82500 20.57750 35.36410
O1 16.50660 19.41590 36.09540
O1 12.10500 15.94220 36.66400
O1 11.89790 23.09930 33.48370
O1 8.85180 20.01320 33.03070
O1 3.35890 26.46080 28.91670
O1 28.64390 20.89670 32.38350
O1 19.25140 19.53800 25.69020
O1 27.85180 17.81300 36.36070
O1 24.54600 17.64430 35.01320
O1 24.61250 16.26360 30.25180
O1 23.59500 18.68440 25.03930
O1 29.38450 19.39050 27.42800
O1 28.46230 17.24070 26.13790
O1 23.41900 16.05100 25.41920
O1 20.86450 16.52580 36.60590
O1 28.65670 21.72460 26.25870
O1 24.07660 20.26020 30.45250
O1 23.51340 20.88570 32.97800
O1 22.37070 18.71390 29.08060
O1 20.48550 20.13210 30.34820
O1 26.11670 16.02700 28.10160
O1 22.47400 16.67560 33.47390
O1 24.30780 18.38100 32.39250
O1 24.98480 15.92980 33.05570
O1 21.13840 15.40450 28.41180
O1 24.95080 18.41800 28.61390
O1 20.36590 17.22290 26.62760
O1 19.84780 16.18560 32.57970
O1 18.59980 20.03360 28.22880
O1 21.95970 15.35590 31.17480
O1 27.56780 18.97560 33.92090
O1 18.25610 16.94610 34.51270
O1 23.57590 20.66830 27.81530
O1 26.04620 20.43420 32.22510
O1 27.34590 20.86050 28.41240
O1 18.39400 21.00940 31.92710
O1 25.81340 17.22560 25.50430
O1 27.10130 19.53510 26.06230
O1 27.05980 21.58520 34.41550
O1 29.11540 16.81420 34.24170
O1 20.87060 21.01860 27.34060
O1 21.44420 17.95390 31.43720
O1 29.31650 18.67500 30.85300
O1 18.27440 18.40780 32.23530
O1 26.98480 17.52210 30.14580
O1 18.36090 17.01020 24.92320
O1 28.96900 16.10330 31.25790
O1 22.65960 21.21280 25.33510
O1 29.91780 19.12600 35.25310
O1 29.28310 17.01420 28.74410
O1 18.52530 15.75640 28.00480
O1 31.07110 17.39660 26.77800
O1 19.93120 17.66810 29.24750
O1 2.17270 24.11650 26.29840
O1 9.58600 16.68330 36.18440
O1 8.66650 24.44530 29.13340
O1 9.26790 17.04160 33.05810
O1 22.57750 23.05970 27.25190
O1 23.55110 22.26680 36.19210
O1 21.05710 21.35860 36.38970
O1 10.23460 20.81100 37.74490
O1 6.24970 29.29580 37.90810
O1 6.02800 26.74740 38.68470
O1 2.41570 26.61210 37.21420
O1 12.99070 24.93300 40.13400
O1 15.10430 21.96080 36.66910
O1 14.35630 18.25820 37.20960
O1 8.15500 19.37870 38.71870
O1 4.36060 24.81290 37.76790
O1 8.30520 22.05750 39.06950
O1 12.61200 20.96490 36.62590
O1 11.42360 18.50900 36.86540
O1 10.93280 24.02310 38.68800
O1 14.31130 20.46650 38.69260
O1 4.60390 25.28430 40.39890
O1 8.64450 24.19920 37.37490
O1 8.25910 27.64210 37.49410
O1 11.97980 22.53100 40.63070
O1 13.37770 22.96530 38.36710
O1 6.58060 24.11570 39.07690
O1 19.72680 18.46060 38.03610
O1 23.10600 19.63860 36.13660
O1 26.83420 17.30090 38.77090
O1 23.41610 17.31220 37.41820
O1 18.56870 20.84910 38.36710
O1 25.50910 18.95900 37.12850
O1 27.80600 19.70350 38.28890
O1 18.23990 16.37600 37.16320
O1 1.76600 24.25350 38.27130
O1 4.61090 29.86330 32.52900
end
constraints slab
fix atom 173 174:698
end
set constraints slab
BASIS "ao basis" PRINT

    BASIS SET: (4s,1p) -> [2s,1p]

H S

    13.0100000              0.0196850        

     1.9620000              0.1379770        

     0.4446000              0.4781480        

H S

     0.1220000              1.0000000        

H P

     0.7270000              1.0000000        

    BASIS SET: (9s,4p,1d) -> [3s,2p,1d]

C S

  6665.0000000              0.0006920             -0.0001460        

  1000.0000000              0.0053290             -0.0011540        

   228.0000000              0.0270770             -0.0057250        

    64.7100000              0.1017180             -0.0233120        

    21.0600000              0.2747400             -0.0639550        

     7.4950000              0.4485640             -0.1499810        

     2.7970000              0.2850740             -0.1272620        

     0.5215000              0.0152040              0.5445290        

C S

     0.1596000              1.0000000        

C P

     9.4390000              0.0381090        

     2.0020000              0.2094800        

     0.5456000              0.5085570        

C P

     0.1517000              1.0000000        

C D

     0.5500000              1.0000000        

    BASIS SET: (9s,4p,1d) -> [3s,2p,1d]

N S

  9046.0000000              0.0007000             -0.0001530        

  1357.0000000              0.0053890             -0.0012080        

   309.3000000              0.0274060             -0.0059920        

    87.7300000              0.1032070             -0.0245440        

    28.5600000              0.2787230             -0.0674590        

    10.2100000              0.4485400             -0.1580780        

     3.8380000              0.2782380             -0.1218310        

     0.7466000              0.0154400              0.5490030        

N S

     0.2248000              1.0000000        

N P

    13.5500000              0.0399190        

     2.9170000              0.2171690        

     0.7973000              0.5103190        

N P

     0.2185000              1.0000000        

N D

     0.8170000              1.0000000        

    BASIS SET: (9s,4p,1d) -> [3s,2p,1d]

O S

 11720.0000000              0.0007100             -0.0001600        

  1759.0000000              0.0054700             -0.0012630        

   400.8000000              0.0278370             -0.0062670        

   113.7000000              0.1048000             -0.0257160        

    37.0300000              0.2830620             -0.0709240        

    13.2700000              0.4487190             -0.1654110        

     5.0250000              0.2709520             -0.1169550        

     1.0130000              0.0154580              0.5573680        

O S

     0.3023000              1.0000000        

O P

    17.7000000              0.0430180        

     3.8540000              0.2289130        

     1.0460000              0.5087280        

O P

     0.2753000              1.0000000        

O D

     1.1850000              1.0000000       

    BASIS SET: (10s,6p,1d) -> [3s,3p,1d] lanl2dzdp

O1 S

  7817.0000000              0.0011760        

  1176.0000000              0.0089680        

   273.2000000              0.0428680        

    81.1700000              0.1439300        

    27.1800000              0.3556300        

     9.5320000              0.4612480        

     3.4140000              0.1402060        

O1 S

     9.5320000             -0.1541530        

     0.9398000              1.0569140        

O1 S

     0.2846000              1.0000000        

O1 P

    35.1800000              0.0195800        

     7.9040000              0.1242000        

     2.3050000              0.3947140        

     0.7171000              0.6273760        

O1 P

     0.2137000              1.0000000        

O1 P

     0.0673000              1.0000000        

O1 D

     0.9610000              1.0000000        

    BASIS SET: (3s,4p,1d) -> [2s,3p,1d] lanl2dzdp

Si1 S

     1.2220000             -0.5707339        

     0.2595000              1.2823826        

Si1 S

     0.0931000              1.0000000        

Si1 P

     2.5800000             -0.0777250        

     0.2984000              1.0197870        

Si1 P

     0.0885000              1.0000000        

Si1 P

     0.0237000              1.0000000        

Si1 D

     0.2960000              1.0000000      

end
ECP
Si1 nelec 10
Si1 ul
1 505.3137693 -10.0000000
2 103.2221026 -84.9236087
2 23.4569248 -30.3299410
2 6.7505693 -12.1049046
2 2.1603140 -1.8945408
Si1 S
0 689.4910719 3.0000000
1 114.1728510 60.5206833
2 35.7424336 201.3086137
2 9.4529586 65.9399745
2 2.2543590 19.0300789
Si1 P
0 88.9379355 5.0000000
1 76.7773538 6.6413817
2 56.1480987 247.5972416
2 21.1874014 129.3715380
2 6.8277276 47.4617107
2 2.1001192 11.7376574
end
driver
maxiter 400
end
dft
xc b3lyp
disp vdw 3
convergence energy 1d-8
grid fine
maxiter 300
convergence damp 20 lshift .6
end
task dft optimize

**Comment by edoapra** [comment] 2018-05-07 20:16
This bug has been fixed in 
https://github.com/nwchemgit/nwchem/commit/2e230bf7a21f3ca210876655ea8f5e21f5af234a for the master branch and in
https://github.com/nwchemgit/nwchem/commit/7ee64cd1da3c597f746f3cf8ba0a37cf82b1ae94 for the hotfix/release-6-8 branch
Please use the hotfix/release-6-8 branch

**Comment by xiongyan21** [comment] 2018-05-13 04:37
Is this bug caused by this large system, or  should we fix it for every calculation?

**Comment by edoapra** [comment] 2018-06-04 22:17
@xiongyan21 the bug shows up when the number of fixed atoms is greater than 100

**Closed by edoapra** 2018-06-04 22:17 UTC
