### ISSUE TITLE
Failing to build 7.0.0beta1 without python

### ISSUE THREAD

**Issue by ckoe-bccms** [nwchemgit/nwchem#178] opened 2020-02-04 15:53 UTC
Hello everybody,

I am trying to build 7.0.0beta1 without python support as I am not interested in it. This fails, see below. I was not able to find anything in the release notes for 7.0.0 or the wiki about how to not use python but a lot about how to use it optionally, so I am unsure if this behaviour during build might be unintended.

Extracting from the nwchem-7.0.0-release.revision-5bcf0416-src.2019-11-01.tar.bz2 and then running this script
```
export NWCHEM_TOP=$PWD
export NWCHEM_TARGET=LINUX64
export USE_64TO32=y
export BLAS_SIZE=4
export USE_MPI=yes
export USE_MPIF=yes
export USE_MPIF4=yes
export LARGE_FILES=TRUE
export BLASOPT="-L/cluster/OpenBLAS/0.3.7/gcc9/lib/ -lopenblas_omp -lpthread -lrt"
export LAPACK_LIB="-L/cluster/OpenBLAS/0.3.7/gcc9/lib/ -lopenblas_omp -lpthread -lrt"
export ARMCI_NETWORK=MPI-TS
cd $NWCHEM_TOP/src
make clean
export NWCHEM_MODULES="qm"
make nwchem_config
```
errors out
```
python-config not found in your PATH
Please install the packages
python3-dev  (Ubuntu/Debian) or
python3-devel (Redhat/Fedora/Centos)

config/makefile.h:2596: *** .  Stop.
```

What do I have to do if I do not want to build with python support ? Or is python  a build requirement ? 
Of course the build proceeds if I load one of our python environment modules, we do not have python distribution packages installed (as far as possible) on purpose.

Also, above settings worked fine with nwchem-6.8-release.revision-v6.8-47-gdf6c956-src, no problems with any python requirements as far as I can tell.

**Comment by edoapra** [comment] 2020-02-04 18:11
@ckoe-bccms thanks for the bug report
Could you please send me the output of the command
```
grep -i python $NWCHEM_TOP/src/stubs.F
```

**Comment by ckoe-bccms** [comment] 2020-02-05 09:04
Hello !

Here is the complete output in a fresh shell with no modules loaded and no environment variables set manually before
```
node045 9:59 ~ % cd src 
node045 9:59 ~/src % tar -jxf nwchem-7.0.0-release.revision-5bcf0416-src.2019-11
-01.tar.bz2
node045 10:02 ~/src % cd  nwchem-7.0.0
node045 10:02 ~/src/nwchem-7.0.0 % export NWCHEM_TOP=$PWD
node045 10:03 ~/src/nwchem-7.0.0 % export NWCHEM_TARGET=LINUX64
node045 10:03 ~/src/nwchem-7.0.0 % export USE_64TO32=y
node045 10:03 ~/src/nwchem-7.0.0 % export BLAS_SIZE=4
node045 10:03 ~/src/nwchem-7.0.0 % export USE_MPI=yes
node045 10:03 ~/src/nwchem-7.0.0 % export USE_MPIF=yes
node045 10:03 ~/src/nwchem-7.0.0 % export USE_MPIF4=yes
node045 10:03 ~/src/nwchem-7.0.0 % export LARGE_FILES=TRUE
node045 10:03 ~/src/nwchem-7.0.0 % export BLASOPT="-L/cluster/OpenBLAS/0.3.7/gcc
9/lib/ -lopenblas_omp -lpthread -lrt"
node045 10:03 ~/src/nwchem-7.0.0 % export LAPACK_LIB="-L/cluster/OpenBLAS/0.3.7/
gcc9/lib/ -lopenblas_omp -lpthread -lrt"
node045 10:03 ~/src/nwchem-7.0.0 % export ARMCI_NETWORK=MPI-TS
node045 10:03 ~/src/nwchem-7.0.0 % cd $NWCHEM_TOP/src
node045 10:03 ~/src/nwchem-7.0.0/src % make clean

python-config not found in your PATH
Please install the packages
python2-dev  (Ubuntu/Debian) or
python2-devel (Redhat/Fedora/Centos)

config/makefile.h:2596: *** .  Stop.
node045 10:03 ~/src/nwchem-7.0.0/src % grep -i python $NWCHEM_TOP/src/stubs.F
node045 10:03 ~/src/nwchem-7.0.0/src % export NWCHEM_MODULES="qm"
node045 10:03 ~/src/nwchem-7.0.0/src % make nwchem_config

python-config not found in your PATH
Please install the packages
python2-dev  (Ubuntu/Debian) or
python2-devel (Redhat/Fedora/Centos)

config/makefile.h:2596: *** .  Stop.
node045 10:03 ~/src/nwchem-7.0.0/src % grep -i python $NWCHEM_TOP/src/stubs.F
node045 10:03 ~/src/nwchem-7.0.0/src %
```

As far as I can see grep returns nothing.

Thank you for your help !

**Comment by ckoe-bccms** [comment] 2020-02-05 09:58
I was wondering why it is python3 in the original post and python2 in the second one. So I tested on the front end machine of the cluster to be sure. Turns out that the front end has python3 (not python3-devel) installed while the nodes have not, they rely on the module:

```
login 10:54 ~/src/nwchem-7.0.0/src % yum list python3
Loaded plugins: fastestmirror, langpacks, versionlock
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
Excluding 1 update due to versionlock (use "yum versionlock status" to show it)
Installed Packages
python3.x86_64                        3.6.8-10.el7                         @base
```
while on the node
```
node045 10:05 ~/src/nwchem-7.0.0/src % yum list python3
Loaded plugins: fastestmirror, versionlock
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
Excluding 1 update due to versionlock (use "yum versionlock status" to show it)
Available Packages
python3.i686                           3.6.8-10.el7                         base
python3.x86_64                         3.6.8-10.el7                         base
```

Finally the complete output on the front end for completeness:
```
login 10:51 ~/src % rm -r nwchem-7.0.0
login 10:51 ~/src % tar -jxf nwchem-7.0.0-release.revision-5bcf0416-src.2019-11-
01.tar.bz2
login 10:52 ~/src % cd  nwchem-7.0.0
login 10:52 ~/src/nwchem-7.0.0 % export NWCHEM_TOP=$PWD
login 10:52 ~/src/nwchem-7.0.0 % export NWCHEM_TARGET=LINUX64
login 10:52 ~/src/nwchem-7.0.0 % export USE_64TO32=y
login 10:52 ~/src/nwchem-7.0.0 % export BLAS_SIZE=4
login 10:52 ~/src/nwchem-7.0.0 % export USE_MPI=yes
login 10:52 ~/src/nwchem-7.0.0 % export USE_MPIF=yes
login 10:52 ~/src/nwchem-7.0.0 % export USE_MPIF4=yes
login 10:52 ~/src/nwchem-7.0.0 % export LARGE_FILES=TRUE
login 10:52 ~/src/nwchem-7.0.0 % export BLASOPT="-L/cluster/OpenBLAS/0.3.7/gcc9/
lib/ -lopenblas_omp -lpthread -lrt"
login 10:52 ~/src/nwchem-7.0.0 % export LAPACK_LIB="-L/cluster/OpenBLAS/0.3.7/gc
c9/lib/ -lopenblas_omp -lpthread -lrt"
login 10:52 ~/src/nwchem-7.0.0 % export ARMCI_NETWORK=MPI-TS
login 10:52 ~/src/nwchem-7.0.0 % cd $NWCHEM_TOP/src
login 10:52 ~/src/nwchem-7.0.0/src % make clean

python-config not found in your PATH
Please install the packages
python3-dev  (Ubuntu/Debian) or
python3-devel (Redhat/Fedora/Centos)

config/makefile.h:2596: *** .  Stop.
login 10:52 ~/src/nwchem-7.0.0/src % grep -i python $NWCHEM_TOP/src/stubs.F
login 10:52 ~/src/nwchem-7.0.0/src % export NWCHEM_MODULES="qm"
login 10:52 ~/src/nwchem-7.0.0/src % make nwchem_config

python-config not found in your PATH
Please install the packages
python3-dev  (Ubuntu/Debian) or
python3-devel (Redhat/Fedora/Centos)

config/makefile.h:2596: *** .  Stop.
login 10:52 ~/src/nwchem-7.0.0/src % grep -i python $NWCHEM_TOP/src/stubs.F
login 10:54 ~/src/nwchem-7.0.0/src % cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

**Comment by edoapra** [comment] 2020-02-05 18:35
@ckoe-bccms Since the `grep` result on `stubs.F` shows that `make nwchem_config` command fails to exclude python from your build, could you please post the full log of the commands
```
export NWCHEM_MODULES=qm
make nwchem_config
```

**Comment by edoapra** [comment] 2020-02-05 18:52
@ckoe-bccms  Please ignore the previous questions. I misread your latest posts

**Comment by edoapra** [comment] 2020-02-05 19:07
@ckoe-bccms Please try the following. 
```
cd  ~/src/nwchem-7.0.0/src
rm -f config/nwchem_config.h config/NWCHEM_CONFIG
export NWCHEM_MODULES=qm
make nwchem_config
```
Let me know if this works for you and thanks for the useful feedback

**Comment by ckoe-bccms** [comment] 2020-02-06 08:59
Hello @edoapra,

thank you very much ! 

This appears to work fine:
```
login 9:27 ~/src % module load gcc/9 mvapich2
login 9:27 ~/src % rm -r nwchem-7.0.0; tar -jxf nwchem-7.0.0-release.revision-5b
cf0416-src.2019-11-01.tar.bz2; cd nwchem-7.0.0
login 9:27 ~/src/nwchem-7.0.0 % export NWCHEM_TOP=$PWD
login 9:27 ~/src/nwchem-7.0.0 % export NWCHEM_TARGET=LINUX64
login 9:27 ~/src/nwchem-7.0.0 % export USE_64TO32=y
login 9:27 ~/src/nwchem-7.0.0 % export BLAS_SIZE=4
login 9:27 ~/src/nwchem-7.0.0 % export USE_MPI=yes
login 9:27 ~/src/nwchem-7.0.0 % export USE_MPIF=yes
login 9:27 ~/src/nwchem-7.0.0 % export USE_MPIF4=yes
login 9:27 ~/src/nwchem-7.0.0 % export LARGE_FILES=TRUE
login 9:27 ~/src/nwchem-7.0.0 % export BLASOPT="-L/cluster/OpenBLAS/0.3.7/gcc9/l
ib/ -lopenblas_omp -lpthread -lrt"
login 9:27 ~/src/nwchem-7.0.0 % export LAPACK_LIB="-L/cluster/OpenBLAS/0.3.7/gcc
9/lib/ -lopenblas_omp -lpthread -lrt"
login 9:27 ~/src/nwchem-7.0.0 % export ARMCI_NETWORK=MPI-TS
login 9:27 ~/src/nwchem-7.0.0 % cd $NWCHEM_TOP/src
login 9:27 ~/src/nwchem-7.0.0/src % rm -f config/nwchem_config.h config/NWCHEM_CONFIG
login 9:28 ~/src/nwchem-7.0.0/src % export NWCHEM_MODULES=qm
login 9:28 ~/src/nwchem-7.0.0/src % make nwchem_config
config/makefile.h:214: /home1/ckoe/src/nwchem-7.0.0/src/config/nwchem_config.h: 
No such file or directory
make -C config -f make_nwchem_config NWCHEM_MODULES="qm"
make[1]: Entering directory `/home1/ckoe/src/nwchem-7.0.0/src/config'
echo \# This configuration generated automatically on \
      `hostname` at `date` > nwchem_config.h
echo "# Request modules from user: qm" >> nwchem_config.h
echo "NW_MODULE_SUBDIRS = NWints atomscf ddscf gradients moints nwdft rimp2 step
per driver optim cphf ccsd vib mcscf esp hessian dplot mp2_grad property solvati
on vscf etrans tce bq cons dimqm" >> nwchem_config.h
...
...
```
The build completed.

**Comment by edoapra** [comment] 2020-02-06 18:15
@ckoe-bccms Thanks again for the feedback
I have just uploaded a second beta version
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-beta2
that contains a fix for this issue (not requiring the `rm` step you had to perform)
If you have time to download and test this new tar file, your feedback would be extremely useful.
Cheers, Edo

**Comment by ckoe-bccms** [comment] 2020-02-07 15:14
Hello Edo !

Thank you for your efforts. Unfortunately this does not appear to work
```
login 16:05 ~/src % rm -r nwchem-7.0.0; tar -jxf nwchem-7.0.0-release.revision-1832a0c1-src
.2020-02-05.tar.bz2; cd nwchem-7.0.0
login 16:05 ~/src/nwchem-7.0.0 % export NWCHEM_TOP=$PWD
login 16:05 ~/src/nwchem-7.0.0 % export NWCHEM_TARGET=LINUX64
login 16:05 ~/src/nwchem-7.0.0 % export USE_64TO32=y
login 16:05 ~/src/nwchem-7.0.0 % export BLAS_SIZE=4
login 16:05 ~/src/nwchem-7.0.0 % export USE_MPI=yes
login 16:05 ~/src/nwchem-7.0.0 % export USE_MPIF=yes
login 16:05 ~/src/nwchem-7.0.0 % export USE_MPIF4=yes
login 16:05 ~/src/nwchem-7.0.0 % export LARGE_FILES=TRUE
login 16:05 ~/src/nwchem-7.0.0 % export BLASOPT="-L/cluster/OpenBLAS/0.3.7/gcc9/lib/ -lopen
blas_omp -lpthread -lrt"
login 16:05 ~/src/nwchem-7.0.0 % export LAPACK_LIB="-L/cluster/OpenBLAS/0.3.7/gcc9/lib/ -lo
penblas_omp -lpthread -lrt"
login 16:05 ~/src/nwchem-7.0.0 % export ARMCI_NETWORK=MPI-TS
login 16:05 ~/src/nwchem-7.0.0 % cd $NWCHEM_TOP/src
login 16:06 ~/src/nwchem-7.0.0/src % export NWCHEM_MODULES="qm"
login 16:06 ~/src/nwchem-7.0.0/src % make nwchem_config

python-config not found in your PATH
Please install the packages
python3-dev  (Ubuntu/Debian) or
python3-devel (Redhat/Fedora/Centos)

config/makefile.h:2603: *** .  Stop.
login 16:06 ~/src/nwchem-7.0.0/src % 
```

Using the "rm method" in a fresh shell I get
```
login 16:08 ~/src % rm -r nwchem-7.0.0; tar -jxf nwchem-7.0.0-release.revision-1832a0c1-src
.2020-02-05.tar.bz2; cd nwchem-7.0.0
rm: cannot remove ‘nwchem-7.0.0’: No such file or directory
login 16:08 ~/src/nwchem-7.0.0 % export NWCHEM_TOP=$PWD
login 16:09 ~/src/nwchem-7.0.0 % cd src 
login 16:09 ~/src/nwchem-7.0.0/src % rm -f config/nwchem_config.h config/NWCHEM_CONFIG
login 16:09 ~/src/nwchem-7.0.0/src % export NWCHEM_MODULES=qm
login 16:09 ~/src/nwchem-7.0.0/src % make nwchem_config
config/makefile.h:221: /home1/ckoe/src/nwchem-7.0.0/src/config/nwchem_config.h: No such fil
e or directory

NWChem's Performance is degraded by not setting BLASOPT
Please consider using ATLAS, GotoBLAS2, OpenBLAS, Intel MKL,
IBM ESSL, AMD ACML, etc. to improve performance.
If you decide to not use a fast implementation of BLAS/LAPACK,
please define USE_INTERNALBLAS=y and the internal Netlib will be used.
make -C config -f make_nwchem_config NWCHEM_MODULES="qm"
make[1]: Entering directory `/home1/ckoe/src/nwchem-7.0.0/src/config'
echo \# This configuration generated automatically on \
...
...
```

Or may be I am doing some step wrong ?

**Comment by edoapra** [comment] 2020-02-07 17:46
@ckoe-bccms Thanks for the feedback
I have reproduce your failure.
Let me try to fix it

**Comment by edoapra** [comment] 2020-02-07 19:50
@ckoe-bccms I have uploaded new versions of the second beta 7.0.0 tarballs
Could you try these new ones, too?
Thanks

**Comment by ckoe-bccms** [comment] 2020-02-10 17:29
Hello Edo !

Yes, this works now. Thank you !

**Comment by edoapra** [comment] 2020-02-10 18:05
@ckoe-bccms Thanks a lot for the feedback

**Closed by edoapra** 2020-02-10 18:05 UTC
