### ISSUE TITLE
QA test autosym fails

### ISSUE THREAD

**Issue by zyzhang1992** [nwchemgit/nwchem#357] opened 2021-04-14 01:07 UTC
**Describe the bug**
   iter   nsub   residual    time
   ----  ------  --------  ---------
     1     15    7.46D-02       3.9
 ------------------------------------------------------------------------
 gasvd:d: failed     140720308486144
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line :
  1463: task scf freq
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 For more information see the NWChem manual at
 https://github.com/nwchemgit/nwchem/wiki

 For further details see manual section:

**Describe settings used**
Report all the environment variables used.
Report what operating system and distribution you are using.

**Attach log files**
Attach as many log files as possible.
* stdout/stderr of the NWChem execution
* complete makefile log
* $NWCHEM_TOP/src/tools/build/config.log
* $NWCHEM_TOP/src/tools/build/comex/config.log
* debugging stack

**To Reproduce**
1. Steps to reproduce the behavior:
2. Attach all the input files required to run.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by edoapra** [comment] 2021-04-14 01:12
This is likely to be caused by incorrect settings for the linear algebra libraries.

Please provide details of compilation
* NWChem version
* compiler
* settings for blas/lapack, etc ...
* all the env. variables

**Comment by zyzhang1992** [comment] 2021-04-14 04:46
nwchem-7.0.0
    nwchem branch   = 7.0.0
    nwchem revision = 2c9a1c7c
    ga revision     = 5.7.1
    use scalapack   = F

intel/18.0.2      impi/18.0.2
export NWCHEM_LONG_PATHS=Y
export NWCHEM_TOP=$PWD/nwchem-7.0.0
export NWCHEM_MODULES="all python"
export NWCHEM_TARGET="LINUX64"
export TARGET="LINUX64"

export ARMCI_NETWORK="MPI-PR"
export USE_MPI="y"

export LARGE_FILES="TRUE"
export LIB_DEFINES="-DDFLT_TOT_MEM=16777216"
export USE_NOIO="TRUE"
export USE_NOFSCHECK="TRUE"
export MA_USE_ARMCI_MEM="1"

export USE_OPENMP="1"
#you may need to set OMP_STACKSIZE=32M at run time
export MRCC_METHODS="TRUE"

export PYTHONHOME=/opt/apps/intel17/python2/2.7.14/
export PYTHONVERSION=2.7
export USE_PYTHON="y"
export USE_PYTHONCONFIG=Y


#export USE_INTERNALBLAS=y
# set performance math lib
export USE_64TO32=y
export USE_SCALAPACK=y
export BLASOPT=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_l
p64 -liomp5 -lpthread -lm -ldl"
export LAPACK_LIB=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmp
i_lp64 -liomp5 -lpthread -lm -ldl"

export SCALAPACK=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi
_lp64 -liomp5 -lpthread -lm -ldl"

#zz rm -rf nwchem-7.0.0
#zz tar xvf nwchem-7.0.0-release.revision-2c9a1c7c-srconly.2020-02-26.tar.bz2


# set the fat AVX options
export USE_KNL=y
# This will make KNL only code, we need to replace axMIC-AVX512 by general fat option as
# -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512
# this will extend to general many core archs, Haswell, KNL and SKX
sed -i 's/-xMIC-AVX512/-xCORE-AVX2 -axCORE-AVX512,MIC-AVX512/g' $NWCHEM_TOP/src/config/makefile.h
#


cd $NWCHEM_TOP/src
make nwchem_config
make 64_to_32 FC=ifort CC=icc

**Comment by edoapra** [comment] 2021-04-14 16:25
You have not set `BLAS_SIZE` and `SCALAPACK_SIZE`.
Since the default value is 8 and you have chosen LP64, your settings do not work.
Another non optimal setting is the choice of threaded MKL. They degrade performance for most NWChem modules (we are working at fixing this on the master branch)
It is not a good idea to edit `makefile.h` before you have a stable installation (e.g. AVX changes)
Please do the following
```
export BLASOPT=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
export LAPACK_LIB=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
export SCALAPACK=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
export BLAS_SIZE=8
export SCALAPACK_SIZE=8
cd $NWCHEM_TOP/src/tools
rm -rf build install
make FC=ifort
cd ..
make FC=ifort link
```

**Comment by zyzhang1992** [comment] 2021-04-14 22:53
Thanks Edo! 

If I want to use a debugger and want to access the source files, what modifications to the makefile I need? It converts the files to .f and then delete the .f files by default after the build. Do I need to preserve the .f files and how?

**Comment by edoapra** [comment] 2021-04-14 23:10
`.F` files should be all you need for the current compilers since `.f` files are never actually produced and the combination of compiler/debugger can refer to the `.F` files.
What compiler do you plan to use?
PS. Please stop using github issue for this reports since they are not bug reports.
You should be using the nwchem-forum  at https://groups.google.com/forum/#!forum/nwchem-forum
This item is a duplicate of topics already discussed in the forum

**Closed by edoapra** 2021-04-14 23:10 UTC
